M:text_manager
F:G$engine_text_manager_args$0$0({2}DF,SV:S),Z,0,2,0,0,0
S:Ltext_manager.engine_text_manager_args$x$1$7({1}SC:U),B,1,4
S:Ltext_manager.engine_text_manager_args$y$1$7({1}SC:U),B,1,5
S:Ltext_manager.engine_text_manager_args$num$1$7({1}SC:U),B,1,6
S:Ltext_manager.engine_text_manager_args$ch$1$8({1}SC:U),R,0,0,[e]
S:Ltext_manager.engine_text_manager_args$idx$1$8({1}SC:U),R,0,0,[b]
S:Ltext_manager.engine_text_manager_args$arglist$1$8({2}DG,SC:U),B,1,-2
F:G$engine_text_manager_list$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Ltext_manager.engine_text_manager_list$x$1$13({1}SC:U),B,1,4
S:Ltext_manager.engine_text_manager_list$y$1$13({1}SC:U),B,1,5
S:Ltext_manager.engine_text_manager_list$num$1$13({1}SC:U),B,1,6
S:Ltext_manager.engine_text_manager_list$arr$1$13({2}DG,SI:U),B,1,7
S:Ltext_manager.engine_text_manager_list$ch$1$14({1}SC:U),R,0,0,[e]
S:Ltext_manager.engine_text_manager_list$idx$1$14({1}SC:U),R,0,0,[b]
S:G$engine_font_manager_char$0$0({2}DF,SV:S),C,0,0
S:G$engine_font_manager_text$0$0({2}DF,SV:S),C,0,0
S:G$engine_font_manager_data$0$0({2}DF,SV:S),C,0,0
S:G$engine_font_manager_zero$0$0({2}DF,SV:S),C,0,0
