IMAGE gfx_palette0 "palette0.png" 0
IMAGE gfx_palette1 "palette1.png" 0
IMAGE gfx_battle_enemies "battle_enemies.png" 0
IMAGE gfx_battle_enemies_leshy "battle_enemies_leshy.png" 0
IMAGE gfx_battle_player "battle_player.png" 0
IMAGE gfx_border "border.png" 0
IMAGE gfx_font "font.png" 0
IMAGE gfx_koschey "koschey.png" 0
IMAGE gfx_logo_big "logo_big.png" 0
IMAGE gfx_logo_small "logo_small.png" 0
IMAGE gfx_splash "splash.png" 0
IMAGE gfx_stats_inventory "stats_inventory.png" 0
IMAGE gfx_stats_items "stats_items.png" 0
IMAGE gfx_stats_village "stats_village.png" 0