M:screen_manager
F:G$engine_screen_manager_init$0$0({2}DF,SV:S),Z,0,0,0,0,0
F:G$engine_screen_manager_update$0$0({2}DF,SV:S),Z,0,0,0,0,0
F:Fscreen_manager$draw_turtle$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Fscreen_manager$tx$0$0({1}SC:U),E,0,0
S:Fscreen_manager$ty$0$0({1}SC:U),E,0,0
S:Fscreen_manager$flag$0$0({1}SC:U),E,0,0
S:Fscreen_manager$timer$0$0({2}SI:U),E,0,0
S:Fscreen_manager$delta$0$0({2}SI:U),E,0,0
S:G$engine_music_manager_play$0$0({2}DF,SV:S),C,0,0
S:G$engine_sound_manager_play$0$0({2}DF,SV:S),C,0,0
S:G$engine_content_manager_load_tiles$0$0({2}DF,SV:S),C,0,0
S:G$engine_content_manager_load_turtle$0$0({2}DF,SV:S),C,0,0
S:G$engine_content_manager_load_sprites$0$0({2}DF,SV:S),C,0,0
S:G$engine_font_manager_draw_char$0$0({2}DF,SV:S),C,0,0
S:G$engine_font_manager_draw_text$0$0({2}DF,SV:S),C,0,0
S:G$engine_font_manager_draw_data$0$0({2}DF,SV:S),C,0,0
S:G$engine_font_manager_draw_zero$0$0({2}DF,SV:S),C,0,0
S:G$engine_input_manager_update$0$0({2}DF,SV:S),C,0,0
S:G$engine_input_manager_hold_up$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_hold_down$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_hold_left$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_hold_right$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_hold_fire1$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_hold_fire2$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_move_up$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_move_down$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_move_left$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_move_right$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_move_fire1$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_move_fire2$0$0({2}DF,SC:U),C,0,0
S:G$engine_turtle_manager_draw_sea$0$0({2}DF,SV:S),C,0,0
S:G$engine_turtle_manager_draw_01$0$0({2}DF,SV:S),C,0,0
S:G$engine_turtle_manager_draw_02$0$0({2}DF,SV:S),C,0,0
