M:select_screen
F:G$screen_select_screen_load$0$0({2}DF,SV:S),Z,0,0,0,0,0
F:G$screen_select_screen_update$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lselect_screen.screen_select_screen_update$screen_type$1$9({2}DG,SC:U),B,1,4
S:Lselect_screen.screen_select_screen_update$selection$1$10({1}SC:U),R,0,0,[]
T:Fselect_screen$tag_struct_aelect_object[({0}S:S$select_index$0$0({3}DA3d,SC:U),Z,0,0)({3}S:S$select_X$0$0({1}SC:U),Z,0,0)({4}S:S$select_Y$0$0({1}SC:U),Z,0,0)({5}S:S$select_min$0$0({1}SC:U),Z,0,0)({6}S:S$select_max$0$0({1}SC:U),Z,0,0)]
S:G$global_select_object$0$0({7}STtag_struct_aelect_object:S),E,0,0
S:G$engine_font_manager_char$0$0({2}DF,SV:S),C,0,0
S:G$engine_font_manager_text$0$0({2}DF,SV:S),C,0,0
S:G$engine_font_manager_data$0$0({2}DF,SV:S),C,0,0
S:G$engine_font_manager_zero$0$0({2}DF,SV:S),C,0,0
S:G$engine_input_manager_update$0$0({2}DF,SV:S),C,0,0
S:G$engine_input_manager_hold_up$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_hold_down$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_hold_left$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_hold_right$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_hold_fire1$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_hold_fire2$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_move_up$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_move_down$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_move_left$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_move_right$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_move_fire1$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_move_fire2$0$0({2}DF,SC:U),C,0,0
S:G$engine_select_manager_init$0$0({2}DF,SV:S),C,0,0
S:G$engine_select_manager_load$0$0({2}DF,SV:S),C,0,0
S:G$engine_select_manager_update$0$0({2}DF,SC:S),C,0,0
