M:splash_screen
F:G$screen_splash_screen_load$0$0({2}DF,SV:S),Z,0,12,0,0,0
S:Lsplash_screen.screen_splash_screen_load$text$1$7({12}DA12d,SC:U),B,1,-12
S:Lsplash_screen.screen_splash_screen_load$x$1$7({1}SC:U),R,0,0,[e]
F:G$screen_splash_screen_update$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lsplash_screen.screen_splash_screen_update$screen_type$1$10({2}DG,SC:U),B,1,4
S:Lsplash_screen.screen_splash_screen_update$input$1$11({1}SC:U),R,0,0,[l]
S:G$engine_font_manager_asci$0$0({2}DF,SV:S),C,0,0
S:G$engine_font_manager_char$0$0({2}DF,SV:S),C,0,0
S:G$engine_font_manager_text$0$0({2}DF,SV:S),C,0,0
S:G$engine_font_manager_data$0$0({2}DF,SV:S),C,0,0
S:G$engine_font_manager_zero$0$0({2}DF,SV:S),C,0,0
S:G$engine_input_manager_update$0$0({2}DF,SV:S),C,0,0
S:G$engine_input_manager_hold_up$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_hold_down$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_hold_left$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_hold_right$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_hold_fire1$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_hold_fire2$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_move_up$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_move_down$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_move_left$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_move_right$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_move_fire1$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_move_fire2$0$0({2}DF,SC:U),C,0,0
