M:title_screen
F:G$screen_title_screen_load$0$0({2}DF,SV:S),Z,0,0,0,0,0
F:G$screen_title_screen_update$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Ltitle_screen.screen_title_screen_update$screen_type$1$20({2}DG,SC:U),B,1,4
T:Ftitle_screen$tag_struct_path_object[({0}S:S$gamer_route$0$0({448}DA8d,DA56d,SC:U),Z,0,0)]
S:G$global_path_object$0$0({448}STtag_struct_path_object:S),E,0,0
S:G$devkit_SMS_init$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_displayOn$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_displayOff$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_mapROMBank$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setBGScrollX$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setBGScrollY$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_enableSRAM$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_enableSRAMBank$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_disableSRAM$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setSpriteMode$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_useFirstHalfTilesforSprites_False$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_useFirstHalfTilesforSprites_True$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_VDPturnOnFeature$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadPSGaidencompressedTiles$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadSTMcompressedTileMap$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadBGPalette$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadSpritePalette$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setSpritePaletteColor$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setNextTileatXY$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setTile$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadTileMap$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_addSprite$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_addSprite_bulk8$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_addSprite_bulk12$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_initSprites$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_finalizeSprites$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_waitForVBlank$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_copySpritestoSAT$0$0({2}DF,SV:S),C,0,0
S:G$devkit_UNSAFE_SMS_copySpritestoSAT$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_queryPauseRequested$0$0({2}DF,SC:U),C,0,0
S:G$devkit_SMS_resetPauseRequest$0$0({2}DF,SV:S),C,0,0
S:G$devkit_isCollisionDetected$0$0({2}DF,SC:U),C,0,0
S:G$devkit_SMS_getKeysStatus$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_A_KEY_UP$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_A_KEY_DOWN$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_A_KEY_LEFT$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_A_KEY_RIGHT$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_A_KEY_1$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_A_KEY_2$0$0({2}DF,SI:U),C,0,0
S:G$devkit_SPRITEMODE_NORMAL$0$0({2}DF,SC:U),C,0,0
S:G$devkit_VDPFEATURE_HIDEFIRSTCOL$0$0({2}DF,SI:U),C,0,0
S:G$engine_asm_manager_clear_VRAM$0$0({2}DF,SV:S),C,0,0
S:G$engine_content_manager_load_tiles$0$0({2}DF,SV:S),C,0,0
S:G$engine_content_manager_load_sprites$0$0({2}DF,SV:S),C,0,0
S:G$engine_content_manager_load_splash$0$0({2}DF,SV:S),C,0,0
S:G$engine_input_manager_update$0$0({2}DF,SV:S),C,0,0
S:G$engine_input_manager_hold_up$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_hold_down$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_hold_left$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_hold_right$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_hold_fire1$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_hold_fire2$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_move_up$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_move_down$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_move_left$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_move_right$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_move_fire1$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_move_fire2$0$0({2}DF,SC:U),C,0,0
S:G$engine_path_manager_init$0$0({2}DF,SV:S),C,0,0
S:G$engine_text_manager_draw$0$0({2}DF,SV:S),C,0,0
S:G$engine_text_manager_names$0$0({2}DF,SV:S),C,0,0
S:G$engine_text_manager_space$0$0({2}DF,SV:S),C,0,0
S:G$engine_tree_manager_draw$0$0({2}DF,SV:S),C,0,0
