WAV sfx_music_intro "music_intro.wav" XGM
WAV sfx_music_boss "music_boss.wav" XGM
WAV sfx_music_over "music_over.wav" XGM
WAV sfx_sound_type_1 "sound_type_1.wav" XGM
WAV sfx_sound_type_2 "sound_type_2.wav" XGM
WAV sfx_sound_type_3 "sound_type_3.wav" XGM
WAV sfx_sound_type_4 "sound_type_4.wav" XGM
WAV sfx_sound_type_5 "sound_type_5.wav" XGM
WAV sfx_sound_type_6 "sound_type_6.wav" XGM
WAV sfx_sound_type_7 "sound_type_7.wav" XGM
WAV sfx_sound_type_8 "sound_type_8.wav" XGM
WAV sfx_sound_type_9 "sound_type_9.wav" XGM
WAV sfx_sound_type_10 "sound_type_10.wav" XGM
WAV sfx_sound_type_11 "sound_type_11.wav" XGM
WAV sfx_sound_type_12 "sound_type_12.wav" XGM
WAV sfx_sound_type_13 "sound_type_13.wav" XGM
