M:function_manager
F:G$engine_function_manager_convertXYtoZ$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lfunction_manager.engine_function_manager_convertXYtoZ$divide$1$5({1}SC:U),B,1,4
S:Lfunction_manager.engine_function_manager_convertXYtoZ$x$1$5({1}SC:U),B,1,5
S:Lfunction_manager.engine_function_manager_convertXYtoZ$y$1$5({1}SC:U),B,1,6
S:Lfunction_manager.engine_function_manager_convertXYtoZ$z$1$5({2}DG,SC:U),B,1,7
F:G$engine_function_manager_convertZtoXY$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lfunction_manager.engine_function_manager_convertZtoXY$divide$1$7({1}SC:U),B,1,4
S:Lfunction_manager.engine_function_manager_convertZtoXY$z$1$7({1}SC:U),B,1,5
S:Lfunction_manager.engine_function_manager_convertZtoXY$x$1$7({2}DG,SC:U),B,1,6
S:Lfunction_manager.engine_function_manager_convertZtoXY$y$1$7({2}DG,SC:U),B,1,8
F:G$engine_function_manager_convertByteToNibbles$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lfunction_manager.engine_function_manager_convertByteToNibbles$byte$1$9({1}SC:U),B,1,4
S:Lfunction_manager.engine_function_manager_convertByteToNibbles$upper_nibble$1$9({2}DG,SC:U),B,1,5
S:Lfunction_manager.engine_function_manager_convertByteToNibbles$lower_nibble$1$9({2}DG,SC:U),B,1,7
F:G$engine_function_manager_convertNibblesToByte$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lfunction_manager.engine_function_manager_convertNibblesToByte$upper_nibble$1$11({1}SC:U),B,1,4
S:Lfunction_manager.engine_function_manager_convertNibblesToByte$lower_nibble$1$11({1}SC:U),B,1,5
S:Lfunction_manager.engine_function_manager_convertNibblesToByte$byte$1$11({2}DG,SC:U),B,1,6
