M:screen_manager
F:G$engine_screen_manager_init$0$0({2}DF,SV:S),Z,0,0,0,0,0
F:G$engine_screen_manager_update$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lscreen_manager.engine_screen_manager_update$delta$1$21({1}SC:U),R,0,0,[]
S:Lscreen_manager.engine_screen_manager_update$input$1$21({1}SC:U),R,0,0,[l]
F:Fscreen_manager$bonus_level$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lscreen_manager.bonus_level$col$1$27({1}SC:U),R,0,0,[]
S:Lscreen_manager.bonus_level$max$1$27({1}SC:U),R,0,0,[]
F:Fscreen_manager$bonus_level_org$0$0({2}DF,SV:S),C,0,0,0,0,0
S:Fscreen_manager$x$0$0({1}SC:U),E,0,0
S:Fscreen_manager$y$0$0({1}SC:U),E,0,0
S:G$engine_music_manager_play$0$0({2}DF,SV:S),C,0,0
S:G$engine_sound_manager_play$0$0({2}DF,SV:S),C,0,0
S:G$engine_content_manager_load_bgtiles$0$0({2}DF,SV:S),C,0,0
S:G$engine_content_manager_load_sprites$0$0({2}DF,SV:S),C,0,0
S:G$engine_font_manager_draw_char$0$0({2}DF,SV:S),C,0,0
S:G$engine_font_manager_draw_text$0$0({2}DF,SV:S),C,0,0
S:G$engine_font_manager_draw_data$0$0({2}DF,SV:S),C,0,0
S:G$engine_font_manager_draw_zero$0$0({2}DF,SV:S),C,0,0
S:G$engine_input_manager_update$0$0({2}DF,SV:S),C,0,0
S:G$engine_input_manager_hold_up$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_hold_down$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_hold_left$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_hold_right$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_hold_fire1$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_hold_fire2$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_move_up$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_move_down$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_move_left$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_move_right$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_move_fire1$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_move_fire2$0$0({2}DF,SC:U),C,0,0
S:G$engine_tile_manager_seaX$0$0({2}DF,SV:S),C,0,0
S:G$engine_tile_manager_draw_normX$0$0({2}DF,SV:S),C,0,0
S:G$engine_tile_manager_draw_flipX$0$0({2}DF,SV:S),C,0,0
S:G$engine_tile_manager_draw_offsetX$0$0({2}DF,SV:S),C,0,0
S:G$engine_tile_manager_draw_scrollX$0$0({2}DF,SV:S),C,0,0
S:G$engine_tile_manager_draw_turtleX$0$0({2}DF,SV:S),C,0,0
S:G$engine_sprite_manager_draw$0$0({2}DF,SV:S),C,0,0
S:G$engine_sprite_manager_fish$0$0({2}DF,SV:S),C,0,0
S:G$engine_tile_manager_sky$0$0({2}DF,SV:S),C,0,0
S:G$engine_tile_manager_sea$0$0({2}DF,SV:S),C,0,0
S:G$engine_tile_manager_draw_pipe$0$0({2}DF,SV:S),C,0,0
S:G$engine_tile_manager_draw_tile$0$0({2}DF,SV:S),C,0,0
S:G$engine_tile_manager_draw_norm$0$0({2}DF,SV:S),C,0,0
S:G$engine_tile_manager_draw_flip$0$0({2}DF,SV:S),C,0,0
S:G$engine_tile_manager_turtle$0$0({2}DF,SV:S),C,0,0
S:G$engine_tile_manager_sign$0$0({2}DF,SV:S),C,0,0
S:G$engine_tile_manager_scroll_test$0$0({2}DF,SV:S),C,0,0
S:Fscreen_manager$bonus_level_org$0$0({2}DF,SV:S),C,0,0
