M:sprite_manager
F:G$engine_tile_manager_seaX$0$0({2}DF,SV:S),Z,0,4,0,0,0
S:Lsprite_manager.engine_tile_manager_seaX$equator$1$71({1}SC:U),B,1,4
S:Lsprite_manager.engine_tile_manager_seaX$tiles$1$72({2}DG,SC:U),R,0,0,[]
S:Lsprite_manager.engine_tile_manager_seaX$array$1$72({2}DG,SC:U),R,0,0,[c,b]
S:Lsprite_manager.engine_tile_manager_seaX$wide$1$72({1}SC:U),R,0,0,[e]
S:Lsprite_manager.engine_tile_manager_seaX$high$1$72({1}SC:U),R,0,0,[]
S:Lsprite_manager.engine_tile_manager_seaX$idx$1$72({1}SC:U),R,0,0,[l]
S:Lsprite_manager.engine_tile_manager_seaX$val$1$72({1}SC:U),B,1,-7
S:Lsprite_manager.engine_tile_manager_seaX$row$1$72({1}SC:U),R,0,0,[d]
S:Lsprite_manager.engine_tile_manager_seaX$col$1$72({1}SC:U),B,1,-8
S:Lsprite_manager.engine_tile_manager_seaX$mul$1$72({1}SC:U),B,1,-9
S:Lsprite_manager.engine_tile_manager_seaX$x$1$72({1}SC:U),R,0,0,[]
S:Lsprite_manager.engine_tile_manager_seaX$y$1$72({1}SC:U),B,1,-6
S:Lsprite_manager.engine_tile_manager_seaX$sloc0$1$0({1}SC:U),B,1,-4
S:Lsprite_manager.engine_tile_manager_seaX$sloc1$1$0({1}SC:U),B,1,-5
S:Lsprite_manager.engine_tile_manager_seaX$sloc2$1$0({1}SC:U),B,1,-1
S:Lsprite_manager.engine_tile_manager_seaX$sloc3$1$0({2}SI:S),B,1,-3
F:G$engine_tile_manager_draw_normX$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lsprite_manager.engine_tile_manager_draw_normX$type$1$79({1}SC:U),B,1,4
S:Lsprite_manager.engine_tile_manager_draw_normX$x$1$79({1}SC:U),B,1,5
S:Lsprite_manager.engine_tile_manager_draw_normX$y$1$79({1}SC:U),B,1,6
F:G$engine_tile_manager_draw_offsetX$0$0({2}DF,SV:S),Z,0,7,0,0,0
S:Lsprite_manager.engine_tile_manager_draw_offsetX$type$1$81({1}SC:U),B,1,4
S:Lsprite_manager.engine_tile_manager_draw_offsetX$offset$1$81({1}SC:U),B,1,5
S:Lsprite_manager.engine_tile_manager_draw_offsetX$x$1$81({1}SC:U),B,1,6
S:Lsprite_manager.engine_tile_manager_draw_offsetX$y$1$81({1}SC:U),B,1,7
S:Lsprite_manager.engine_tile_manager_draw_offsetX$tiles$1$82({2}DG,SC:U),R,0,0,[]
S:Lsprite_manager.engine_tile_manager_draw_offsetX$array$1$82({2}DG,SC:U),B,1,-6
S:Lsprite_manager.engine_tile_manager_draw_offsetX$wide$1$82({1}SC:U),B,1,-7
S:Lsprite_manager.engine_tile_manager_draw_offsetX$high$1$82({1}SC:U),B,1,-4
S:Lsprite_manager.engine_tile_manager_draw_offsetX$idx$1$82({1}SC:U),R,0,0,[e]
S:Lsprite_manager.engine_tile_manager_draw_offsetX$val$1$82({1}SC:U),R,0,0,[b]
S:Lsprite_manager.engine_tile_manager_draw_offsetX$row$1$82({1}SC:U),B,1,-3
S:Lsprite_manager.engine_tile_manager_draw_offsetX$col$1$82({1}SC:U),R,0,0,[c]
S:Lsprite_manager.engine_tile_manager_draw_offsetX$spc$1$82({1}SC:U),B,1,-8
S:Lsprite_manager.engine_tile_manager_draw_offsetX$tmp$1$82({1}SC:U),B,1,-9
S:Lsprite_manager.engine_tile_manager_draw_offsetX$sloc0$1$0({1}SC:U),B,1,-2
S:Lsprite_manager.engine_tile_manager_draw_offsetX$sloc1$1$0({1}SC:U),B,1,-1
F:G$engine_tile_manager_draw_flipX$0$0({2}DF,SV:S),Z,0,8,0,0,0
S:Lsprite_manager.engine_tile_manager_draw_flipX$type$1$87({1}SC:U),B,1,4
S:Lsprite_manager.engine_tile_manager_draw_flipX$x$1$87({1}SC:U),B,1,5
S:Lsprite_manager.engine_tile_manager_draw_flipX$y$1$87({1}SC:U),B,1,6
S:Lsprite_manager.engine_tile_manager_draw_flipX$tiles$1$88({2}DG,SC:U),R,0,0,[]
S:Lsprite_manager.engine_tile_manager_draw_flipX$array$1$88({2}DG,SC:U),B,1,-8
S:Lsprite_manager.engine_tile_manager_draw_flipX$wide$1$88({1}SC:U),B,1,-6
S:Lsprite_manager.engine_tile_manager_draw_flipX$high$1$88({1}SC:U),B,1,-10
S:Lsprite_manager.engine_tile_manager_draw_flipX$idx$1$88({1}SC:U),R,0,0,[e]
S:Lsprite_manager.engine_tile_manager_draw_flipX$val$1$88({1}SC:U),R,0,0,[b]
S:Lsprite_manager.engine_tile_manager_draw_flipX$row$1$88({1}SC:U),B,1,-5
S:Lsprite_manager.engine_tile_manager_draw_flipX$col$1$88({1}SC:U),R,0,0,[b]
S:Lsprite_manager.engine_tile_manager_draw_flipX$spc$1$88({1}SC:U),B,1,-9
S:Lsprite_manager.engine_tile_manager_draw_flipX$tmp$1$88({1}SC:U),R,0,0,[c]
S:Lsprite_manager.engine_tile_manager_draw_flipX$flip$1$88({2}SI:U),B,1,-4
S:Lsprite_manager.engine_tile_manager_draw_flipX$sloc0$1$0({1}SC:U),B,1,-2
S:Lsprite_manager.engine_tile_manager_draw_flipX$sloc1$1$0({1}SC:U),B,1,-1
F:G$engine_sprite_manager_draw$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lsprite_manager.engine_sprite_manager_draw$x$1$93({1}SC:U),B,1,4
S:Lsprite_manager.engine_sprite_manager_draw$y$1$93({1}SC:U),B,1,5
S:Lsprite_manager.engine_sprite_manager_draw$tile$1$93({2}SI:U),B,1,6
S:Lsprite_manager.engine_sprite_manager_draw$size$1$94({1}SC:U),R,0,0,[]
F:G$engine_sprite_manager_fish$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lsprite_manager.engine_sprite_manager_fish$x$1$95({1}SC:U),B,1,4
S:Lsprite_manager.engine_sprite_manager_fish$y$1$95({1}SC:U),B,1,5
S:Lsprite_manager.engine_sprite_manager_fish$tile$1$96({2}SI:U),R,0,0,[]
S:G$tile_object_data$0$0({0}DA0d,DG,SC:U),E,0,0
S:G$tile_object_dataX$0$0({0}DA0d,DG,SC:U),E,0,0
S:G$devkit_SMS_init$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_VDPturnOnFeature$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_VDPturnOffFeature$0$0({2}DF,SV:S),C,0,0
S:G$devkit_VDPFEATURE_EXTRAHEIGHT$0$0({2}DF,SI:U),C,0,0
S:G$devkit_VDPFEATURE_SHIFTSPRITES$0$0({2}DF,SI:U),C,0,0
S:G$devkit_VDPFEATURE_HIDEFIRSTCOL$0$0({2}DF,SI:U),C,0,0
S:G$devkit_VDPFEATURE_LEFTCOLBLANK$0$0({2}DF,SI:U),C,0,0
S:G$devkit_VDPFEATURE_LOCKHSCROLL$0$0({2}DF,SI:U),C,0,0
S:G$devkit_VDPFEATURE_LOCKVSCROLL$0$0({2}DF,SI:U),C,0,0
S:G$devkit_VDPFEATURE_ZOOMSPRITES$0$0({2}DF,SI:U),C,0,0
S:G$devkit_VDPFEATURE_USETALLSPRITES$0$0({2}DF,SI:U),C,0,0
S:G$devkit_VDPFEATURE_240LINES$0$0({2}DF,SI:U),C,0,0
S:G$devkit_VDPFEATURE_224LINES$0$0({2}DF,SI:U),C,0,0
S:G$devkit_VDPFEATURE_FRAMEIRQ$0$0({2}DF,SI:U),C,0,0
S:G$devkit_VDPFEATURE_SHOWDISPLAY$0$0({2}DF,SI:U),C,0,0
S:G$devkit_SMS_displayOn$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_displayOff$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setBGScrollX$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setBGScrollY$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setBackdropColor$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_useFirstHalfTilesforSprites$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setSpriteMode$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SPRITEMODE_NORMAL$0$0({2}DF,SC:U),C,0,0
S:G$devkit_SPRITEMODE_TALL$0$0({2}DF,SC:U),C,0,0
S:G$devkit_SPRITEMODE_ZOOMED$0$0({2}DF,SC:U),C,0,0
S:G$devkit_SPRITEMODE_TALL_ZOOMED$0$0({2}DF,SC:U),C,0,0
S:G$devkit_SMS_mapROMBank$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_enableSRAM$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_enableSRAMBank$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_disableSRAM$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_SRAM$0$0({2}DF,DG,SC:U),C,0,0
S:G$devkit_SMS_waitForVBlank$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadTiles$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadPSGaidencompressedTiles$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadTileMap$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadSTMcompressedTileMapArea$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadTileMapArea$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadSTMcompressedTileMap$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_crt0_RST08$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_crt0_RST18$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setTile$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setAddr$0$0({2}DF,SV:S),C,0,0
S:G$devkit_XYtoADDR$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setNextTileatXY$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setNextTileatLoc$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setNextTileatAddr$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setTileatXY$0$0({2}DF,SV:S),C,0,0
S:G$devkit_TILE_FLIPPED_X$0$0({2}DF,SI:U),C,0,0
S:G$devkit_TILE_FLIPPED_Y$0$0({2}DF,SI:U),C,0,0
S:G$devkit_TILE_USE_SPRITE_PALETTE$0$0({2}DF,SI:U),C,0,0
S:G$devkit_TILE_PRIORITY$0$0({2}DF,SI:U),C,0,0
S:G$devkit_SMS_initSprites$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_addSprite$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_reserveSprite$0$0({2}DF,SC:S),C,0,0
S:G$devkit_SMS_updateSpritePosition$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_updateSpriteImage$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_hideSprite$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setClippingWindow$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_addSpriteClipping$0$0({2}DF,SC:S),C,0,0
S:G$devkit_SMS_finalizeSprites$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_copySpritestoSAT$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setBGPaletteColor$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setSpritePaletteColor$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadBGPalette$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadSpritePalette$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setNextBGColoratIndex$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setNextSpriteColoratIndex$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setColor$0$0({2}DF,SV:S),C,0,0
S:G$devkit_RGB$0$0({2}DF,SC:U),C,0,0
S:G$devkit_RGB8$0$0({2}DF,SC:U),C,0,0
S:G$devkit_SMS_loadBGPaletteHalfBrightness$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadSpritePaletteHalfBrightness$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_zeroBGPalette$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_zeroSpritePalette$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_getKeysStatus$0$0({2}DF,SI:U),C,0,0
S:G$devkit_SMS_getKeysPressed$0$0({2}DF,SI:U),C,0,0
S:G$devkit_SMS_getKeysHeld$0$0({2}DF,SI:U),C,0,0
S:G$devkit_SMS_getKeysReleased$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_A_KEY_UP$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_A_KEY_DOWN$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_A_KEY_LEFT$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_A_KEY_RIGHT$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_A_KEY_1$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_A_KEY_2$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_A_KEY_START$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_B_KEY_UP$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_B_KEY_DOWN$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_B_KEY_LEFT$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_B_KEY_RIGHT$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_B_KEY_1$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_B_KEY_2$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_B_KEY_START$0$0({2}DF,SI:U),C,0,0
S:G$devkit_RESET_KEY$0$0({2}DF,SI:U),C,0,0
S:G$devkit_CARTRIDGE_SLOT$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_A_TH$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_B_TH$0$0({2}DF,SI:U),C,0,0
S:G$devkit_SMS_queryPauseRequested$0$0({2}DF,SC:U),C,0,0
S:G$devkit_SMS_resetPauseRequest$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_VDPFlags$0$0({2}DF,SC:U),C,0,0
S:G$devkit_VDPFLAG_SPRITEOVERFLOW$0$0({2}DF,SC:U),C,0,0
S:G$devkit_VDPFLAG_SPRITECOLLISION$0$0({2}DF,SC:U),C,0,0
S:G$devkit_SMS_setLineInterruptHandler$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setLineCounter$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_enableLineInterrupt$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_disableLineInterrupt$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_VRAMmemcpy$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_VRAMmemcpy_brief$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_VRAMmemset$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_VRAMmemsetW$0$0({2}DF,SV:S),C,0,0
S:G$devkit_UNSAFE_SMS_copySpritestoSAT$0$0({2}DF,SV:S),C,0,0
S:G$devkit_UNSAFE_SMS_VRAMmemcpy32$0$0({2}DF,SV:S),C,0,0
S:G$devkit_UNSAFE_SMS_VRAMmemcpy64$0$0({2}DF,SV:S),C,0,0
S:G$devkit_UNSAFE_SMS_VRAMmemcpy128$0$0({2}DF,SV:S),C,0,0
S:G$devkit_UNSAFE_SMS_load1Tile$0$0({2}DF,SV:S),C,0,0
S:G$devkit_UNSAFE_SMS_load2Tiles$0$0({2}DF,SV:S),C,0,0
S:G$devkit_UNSAFE_SMS_load4Tiles$0$0({2}DF,SV:S),C,0,0
S:G$dekvit_SMS_isr$0$0({2}DF,SV:S),C,0,0
S:G$dekvit_SMS_nmi_isr$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_addSprite_bulk8$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_addSprite_bulk12$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setTilePriority$0$0({2}DF,SV:S),C,0,0
S:G$devkit_isCollisionDetected$0$0({2}DF,SC:U),C,0,0
