M:scroll_manager
F:G$engine_scroll_manager_load$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lscroll_manager.engine_scroll_manager_load$ytile$1$18({2}SI:U),R,0,0,[c,b]
S:Lscroll_manager.engine_scroll_manager_load$src$3$20({2}DG,SC:U),R,0,0,[e,d]
S:Lscroll_manager.engine_scroll_manager_load$size$3$20({2}SI:S),R,0,0,[l,h]
F:G$engine_scroll_manager_update_left$0$0({2}DF,SV:S),Z,0,2,0,0,0
S:Lscroll_manager.engine_scroll_manager_update_left$ytile$1$21({2}SI:U),R,0,0,[c,b]
S:Lscroll_manager.engine_scroll_manager_update_left$x$5$25({1}SC:U),B,1,-1
S:Lscroll_manager.engine_scroll_manager_update_left$y$5$25({1}SC:U),B,1,-2
S:Lscroll_manager.engine_scroll_manager_update_left$src$5$25({2}DG,SC:U),R,0,0,[l,h]
F:G$engine_scroll_manager_update_right$0$0({2}DF,SV:S),Z,0,2,0,0,0
S:Lscroll_manager.engine_scroll_manager_update_right$ytile$1$26({2}SI:U),R,0,0,[e,d]
S:Lscroll_manager.engine_scroll_manager_update_right$x$5$30({1}SC:U),B,1,-1
S:Lscroll_manager.engine_scroll_manager_update_right$y$5$30({1}SC:U),B,1,-2
S:Lscroll_manager.engine_scroll_manager_update_right$src$5$30({2}DG,SC:U),R,0,0,[]
S:G$BG_TILE_WIDTH$0$0({2}SI:U),E,0,0
S:G$X_TILE_MAX$0$0({2}SI:U),E,0,0
S:G$Y_TILE_MAX$0$0({2}SI:U),E,0,0
S:Fscroll_manager$delta$0$0({1}SC:U),E,0,0
S:Fscroll_manager$scroll$0$0({2}SI:U),E,0,0
S:Fscroll_manager$scrollDivided8$0$0({2}SI:U),E,0,0
S:Fscroll_manager$scrollRight$0$0({2}SI:U),E,0,0
S:Fscroll_manager$scrollRightDivided8$0$0({2}SI:U),E,0,0
S:G$engine_content_manager_load_tiles$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_init$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_displayOn$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_displayOff$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_mapROMBank$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setBGScrollX$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setBGScrollY$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_enableSRAM$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_enableSRAMBank$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_disableSRAM$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setSpriteMode$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_useFirstHalfTilesforSprites_False$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_useFirstHalfTilesforSprites_True$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_VDPturnOnFeature$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadPSGaidencompressedTiles$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadSTMcompressedTileMap$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadBGPalette$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadSpritePalette$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setSpritePaletteColor$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setNextTileatXY$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setTile$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadTileMap$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_addSprite$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_addSprite_bulk8$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_addSprite_bulk12$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_initSprites$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_finalizeSprites$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_waitForVBlank$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_copySpritestoSAT$0$0({2}DF,SV:S),C,0,0
S:G$devkit_UNSAFE_SMS_copySpritestoSAT$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_queryPauseRequested$0$0({2}DF,SC:U),C,0,0
S:G$devkit_SMS_resetPauseRequest$0$0({2}DF,SV:S),C,0,0
S:G$devkit_isCollisionDetected$0$0({2}DF,SC:U),C,0,0
S:G$devkit_SMS_getKeysStatus$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_A_KEY_UP$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_A_KEY_DOWN$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_A_KEY_LEFT$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_A_KEY_RIGHT$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_A_KEY_1$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_A_KEY_2$0$0({2}DF,SI:U),C,0,0
S:G$devkit_SPRITEMODE_NORMAL$0$0({2}DF,SC:U),C,0,0
S:G$devkit_VDPFEATURE_HIDEFIRSTCOL$0$0({2}DF,SI:U),C,0,0
