M:delay_manager
F:G$engine_delay_manager_load$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Ldelay_manager.engine_delay_manager_load$delay$1$2({2}SI:U),B,1,4
S:Ldelay_manager.engine_delay_manager_load$dObj$1$3({2}DG,STtag_struct_delay_object:S),R,0,0,[]
S:Ldelay_manager.engine_delay_manager_load$ho$1$3({2}DG,STtag_struct_hack_object:S),R,0,0,[]
F:G$engine_delay_manager_update$0$0({2}DF,SC:U),Z,0,0,0,0,0
S:Ldelay_manager.engine_delay_manager_update$dObj$1$5({2}DG,STtag_struct_delay_object:S),R,0,0,[]
S:Ldelay_manager.engine_delay_manager_update$test$1$5({1}SC:U),R,0,0,[b]
T:Fdelay_manager$tag_struct_hack_object[({0}S:S$hack_delayspeed$0$0({1}SC:U),Z,0,0)({1}S:S$hack_invincible$0$0({1}SC:U),Z,0,0)({2}S:S$hack_difficulty$0$0({1}SC:U),Z,0,0)({3}S:S$hack_game_speed$0$0({1}SC:U),Z,0,0)({4}S:S$hack_world$0$0({1}SC:U),Z,0,0)({5}S:S$hack_round$0$0({1}SC:U),Z,0,0)({6}S:S$hack_music$0$0({1}SC:U),Z,0,0)({7}S:S$hack_sound$0$0({1}SC:U),Z,0,0)({8}S:S$hack_enemy$0$0({1}SC:U),Z,0,0)]
T:Fdelay_manager$tag_struct_delay_object[({0}S:S$delay_delay$0$0({2}SI:U),Z,0,0)({2}S:S$delay_timer$0$0({2}SI:U),Z,0,0)]
S:G$global_hack_object$0$0({9}STtag_struct_hack_object:S),E,0,0
S:G$global_delay_object$0$0({4}STtag_struct_delay_object:S),E,0,0
S:G$engine_hack_manager_init$0$0({2}DF,SV:S),C,0,0
S:G$engine_hack_manager_invert$0$0({2}DF,SV:S),C,0,0
