M:diff_screen
F:G$screen_diff_screen_load$0$0({2}DF,SV:S),Z,0,0,0,0,0
F:G$screen_diff_screen_update$0$0({2}DF,SV:S),Z,0,5,0,0,0
S:Ldiff_screen.screen_diff_screen_update$screen_type$1$9({2}DG,SC:U),B,1,4
S:Ldiff_screen.screen_diff_screen_update$go$1$10({2}DG,STtag_struct_game_object:S),R,0,0,[]
S:Ldiff_screen.screen_diff_screen_update$test$1$10({5}DA5d,SC:U),B,1,-11
S:Ldiff_screen.screen_diff_screen_update$sloc0$1$0({2}DD,SC:U),B,1,-2
S:Ldiff_screen.screen_diff_screen_update$sloc1$1$0({2}DD,SC:U),B,1,-4
S:Ldiff_screen.screen_diff_screen_update$sloc2$1$0({2}DD,SC:U),B,1,-6
F:Fdiff_screen$display_cursor$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Ldiff_screen.display_cursor$go$1$18({2}DG,STtag_struct_game_object:S),R,0,0,[]
T:Fdiff_screen$tag_struct_game_object[({0}S:S$invincible$0$0({1}SC:U),Z,0,0)({1}S:S$localcheat$0$0({1}SC:U),Z,0,0)({2}S:S$difficulty$0$0({1}SC:U),Z,0,0)({3}S:S$game_speed$0$0({1}SC:U),Z,0,0)({4}S:S$tutorial$0$0({1}SC:U),Z,0,0)({5}S:S$world_no$0$0({1}SC:U),Z,0,0)({6}S:S$round_no$0$0({1}SC:U),Z,0,0)]
S:Fdiff_screen$cursorX$0$0({2}DA2d,SC:U),E,0,0
S:G$count_text$0$0({0}DA0d,DG,SC:U),E,0,0
S:G$lives_text$0$0({0}DA0d,DG,SC:U),E,0,0
S:G$global_game_object$0$0({7}STtag_struct_game_object:S),E,0,0
S:Fdiff_screen$select_count$0$0({1}SC:U),E,0,0
S:G$engine_font_manager_draw_char$0$0({2}DF,SV:S),C,0,0
S:G$engine_font_manager_draw_text$0$0({2}DF,SV:S),C,0,0
S:G$engine_font_manager_draw_data$0$0({2}DF,SV:S),C,0,0
S:G$engine_font_manager_draw_data_ZERO$0$0({2}DF,SV:S),C,0,0
S:G$engine_text_manager_clear_all$0$0({2}DF,SV:S),C,0,0
S:G$engine_text_manager_clear_three$0$0({2}DF,SV:S),C,0,0
S:G$engine_text_manager_cheat_blank$0$0({2}DF,SV:S),C,0,0
S:G$engine_text_manager_cheat_write$0$0({2}DF,SV:S),C,0,0
S:G$engine_text_manager_write_gems$0$0({2}DF,SV:S),C,0,0
S:G$engine_text_manager_write_info$0$0({2}DF,SV:S),C,0,0
S:G$engine_input_manager_update$0$0({2}DF,SV:S),C,0,0
S:G$engine_input_manager_hold_up$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_hold_down$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_hold_left$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_hold_right$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_hold_fire1$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_hold_fire2$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_move_up$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_move_down$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_move_left$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_move_right$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_move_fire1$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_move_fire2$0$0({2}DF,SC:U),C,0,0
S:G$engine_audio_manager_music_game$0$0({2}DF,SV:S),C,0,0
S:G$engine_audio_manager_music_title$0$0({2}DF,SV:S),C,0,0
S:G$engine_audio_manager_music_over$0$0({2}DF,SV:S),C,0,0
S:G$engine_audio_manager_music_beat$0$0({2}DF,SV:S),C,0,0
S:G$engine_audio_manager_music_resume$0$0({2}DF,SV:S),C,0,0
S:G$engine_audio_manager_music_stop$0$0({2}DF,SV:S),C,0,0
S:G$engine_audio_manager_sound_accept$0$0({2}DF,SV:S),C,0,0
S:G$engine_audio_manager_sound_death$0$0({2}DF,SV:S),C,0,0
S:G$engine_audio_manager_sound_gem$0$0({2}DF,SV:S),C,0,0
S:G$engine_audio_manager_sound_level$0$0({2}DF,SV:S),C,0,0
S:G$engine_audio_manager_sound_power$0$0({2}DF,SV:S),C,0,0
S:G$engine_audio_manager_sound_reset$0$0({2}DF,SV:S),C,0,0
S:G$engine_game_manager_init$0$0({2}DF,SV:S),C,0,0
S:G$engine_game_manager_draw$0$0({2}DF,SV:S),C,0,0
