M:init_screen
F:G$screen_init_screen_load$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Linit_screen.screen_init_screen_load$go$1$19({2}DG,STtag_struct_game_object:S),R,0,0,[]
F:G$screen_init_screen_update$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Linit_screen.screen_init_screen_update$screen_type$1$20({2}DG,SC:U),B,1,4
T:Finit_screen$tag_struct_game_object[({0}S:S$invincible$0$0({1}SC:U),Z,0,0)({1}S:S$localcheat$0$0({1}SC:U),Z,0,0)({2}S:S$difficulty$0$0({1}SC:U),Z,0,0)({3}S:S$game_speed$0$0({1}SC:U),Z,0,0)({4}S:S$tutorial$0$0({1}SC:U),Z,0,0)({5}S:S$world_no$0$0({1}SC:U),Z,0,0)({6}S:S$round_no$0$0({1}SC:U),Z,0,0)]
T:Finit_screen$tag_struct_score_object[({0}S:S$tot_lives$0$0({1}SC:U),Z,0,0)({1}S:S$num_lives$0$0({1}SC:U),Z,0,0)({2}S:S$gem_count$0$0({1}SC:U),Z,0,0)({3}S:S$gem_level$0$0({1}SC:U),Z,0,0)({4}S:S$gem_total$0$0({2}SI:U),Z,0,0)]
S:G$global_score_object$0$0({6}STtag_struct_score_object:S),E,0,0
S:G$global_game_object$0$0({7}STtag_struct_game_object:S),E,0,0
S:G$devkit_SMS_init$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_displayOn$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_displayOff$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_mapROMBank$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setSpriteMode$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_useFirstHalfTilesforSprites_False$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_useFirstHalfTilesforSprites_True$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_VDPturnOnFeature$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadPSGaidencompressedTiles$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadSTMcompressedTileMap$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadBGPalette$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadSpritePalette$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setSpritePaletteColor$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setNextTileatXY$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setTile$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_addSprite$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_addSprite_bulk8$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_addSprite_bulk12$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_initSprites$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_finalizeSprites$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_waitForVBlank$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_copySpritestoSAT$0$0({2}DF,SV:S),C,0,0
S:G$devkit_UNSAFE_SMS_copySpritestoSAT$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_queryPauseRequested$0$0({2}DF,SC:U),C,0,0
S:G$devkit_SMS_resetPauseRequest$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_getKeysStatus$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_A_KEY_UP$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_A_KEY_DOWN$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_A_KEY_LEFT$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_A_KEY_RIGHT$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_A_KEY_1$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_A_KEY_2$0$0({2}DF,SI:U),C,0,0
S:G$devkit_SPRITEMODE_NORMAL$0$0({2}DF,SC:U),C,0,0
S:G$devkit_VDPFEATURE_HIDEFIRSTCOL$0$0({2}DF,SI:U),C,0,0
S:G$engine_content_manager_load_back_tiles$0$0({2}DF,SV:S),C,0,0
S:G$engine_content_manager_load_sprites$0$0({2}DF,SV:S),C,0,0
S:G$engine_content_manager_load_splash$0$0({2}DF,SV:S),C,0,0
S:G$engine_content_manager_load_title$0$0({2}DF,SV:S),C,0,0
S:G$engine_content_manager_load_guards$0$0({2}DF,SV:S),C,0,0
S:G$engine_text_manager_clear_all$0$0({2}DF,SV:S),C,0,0
S:G$engine_text_manager_clear_three$0$0({2}DF,SV:S),C,0,0
S:G$engine_text_manager_cheat_blank$0$0({2}DF,SV:S),C,0,0
S:G$engine_text_manager_cheat_write$0$0({2}DF,SV:S),C,0,0
S:G$engine_text_manager_write_gems$0$0({2}DF,SV:S),C,0,0
S:G$engine_text_manager_write_info$0$0({2}DF,SV:S),C,0,0
S:G$engine_anim_manager_player_load_idle$0$0({2}DF,SV:S),C,0,0
S:G$engine_anim_manager_player_load_move$0$0({2}DF,SV:S),C,0,0
S:G$engine_anim_manager_tester_load_anim$0$0({2}DF,SV:S),C,0,0
S:G$engine_anim_manager_enemyX_load_idle$0$0({2}DF,SV:S),C,0,0
S:G$engine_score_manager_init$0$0({2}DF,SV:S),C,0,0
S:G$engine_score_manager_reset_gems$0$0({2}DF,SV:S),C,0,0
S:G$engine_score_manager_reset_lives$0$0({2}DF,SV:S),C,0,0
S:G$engine_score_manager_update_gems$0$0({2}DF,SV:S),C,0,0
S:G$engine_score_manager_bonus_gems$0$0({2}DF,SV:S),C,0,0
S:G$engine_score_manager_update_lives$0$0({2}DF,SV:S),C,0,0
S:G$engine_score_manager_draw_lives$0$0({2}DF,SV:S),C,0,0
S:G$engine_score_manager_draw_score$0$0({2}DF,SV:S),C,0,0
S:G$engine_score_manager_draw_score_at$0$0({2}DF,SV:S),C,0,0
S:G$engine_game_manager_init$0$0({2}DF,SV:S),C,0,0
S:G$engine_game_manager_draw$0$0({2}DF,SV:S),C,0,0
