M:intro_screen
F:G$screen_intro_screen_load$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lintro_screen.screen_intro_screen_load$x$1$52({1}SC:U),R,0,0,[b]
S:Lintro_screen.screen_intro_screen_load$tile$1$52({1}SC:U),R,0,0,[d]
F:G$screen_intro_screen_update$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lintro_screen.screen_intro_screen_update$screen_type$1$55({2}DG,SC:U),B,1,4
S:Lintro_screen.screen_intro_screen_update$delay$1$56({1}SC:U),R,0,0,[c]
S:Lintro_screen.screen_intro_screen_update$input$1$56({1}SC:U),R,0,0,[b]
S:Lintro_screen.screen_intro_screen_update$x$1$56({1}SC:U),R,0,0,[]
S:Lintro_screen.screen_intro_screen_update$y$1$56({1}SC:U),R,0,0,[]
S:Lintro_screen.screen_intro_screen_update$frame$1$56({1}SC:U),R,0,0,[]
F:Fintro_screen$draw_sprite$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lintro_screen.draw_sprite$x$1$59({1}SC:U),B,1,4
S:Lintro_screen.draw_sprite$y$1$59({1}SC:U),B,1,5
S:Lintro_screen.draw_sprite$frame$1$59({2}SI:U),B,1,6
S:Lintro_screen.draw_sprite$tile$1$60({2}SI:U),R,0,0,[l,h]
F:Fintro_screen$update_text$0$0({2}DF,SV:S),Z,0,0,0,0,0
T:Fintro_screen$tag_struct_delay_object[({0}S:S$delay_delay$0$0({2}SI:U),Z,0,0)({2}S:S$delay_timer$0$0({2}SI:U),Z,0,0)]
S:G$intro_textTop$0$0({0}DA0d,DG,SC:U),E,0,0
S:G$intro_textBot$0$0({0}DA0d,DG,SC:U),E,0,0
S:G$count_text$0$0({0}DA0d,DG,SC:U),E,0,0
S:G$lives_text$0$0({0}DA0d,DG,SC:U),E,0,0
S:G$global_delay_object$0$0({4}STtag_struct_delay_object:S),E,0,0
S:Fintro_screen$count$0$0({1}SC:U),E,0,0
S:Fintro_screen$first$0$0({1}SC:U),E,0,0
S:Fintro_screen$stage$0$0({1}SC:U),E,0,0
S:Fintro_screen$pause$0$0({1}SC:U),E,0,0
S:G$devkit_SMS_init$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_displayOn$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_displayOff$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_mapROMBank$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setSpriteMode$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_useFirstHalfTilesforSprites_False$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_useFirstHalfTilesforSprites_True$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_VDPturnOnFeature$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadPSGaidencompressedTiles$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadSTMcompressedTileMap$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadBGPalette$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadSpritePalette$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setSpritePaletteColor$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setNextTileatXY$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setTile$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_addSprite$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_addSprite_bulk8$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_addSprite_bulk12$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_initSprites$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_finalizeSprites$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_waitForVBlank$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_copySpritestoSAT$0$0({2}DF,SV:S),C,0,0
S:G$devkit_UNSAFE_SMS_copySpritestoSAT$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_queryPauseRequested$0$0({2}DF,SC:U),C,0,0
S:G$devkit_SMS_resetPauseRequest$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_getKeysStatus$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_A_KEY_UP$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_A_KEY_DOWN$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_A_KEY_LEFT$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_A_KEY_RIGHT$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_A_KEY_1$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_A_KEY_2$0$0({2}DF,SI:U),C,0,0
S:G$devkit_SPRITEMODE_NORMAL$0$0({2}DF,SC:U),C,0,0
S:G$devkit_VDPFEATURE_HIDEFIRSTCOL$0$0({2}DF,SI:U),C,0,0
S:G$engine_content_manager_load_back_tiles$0$0({2}DF,SV:S),C,0,0
S:G$engine_content_manager_load_sprites$0$0({2}DF,SV:S),C,0,0
S:G$engine_content_manager_load_splash$0$0({2}DF,SV:S),C,0,0
S:G$engine_content_manager_load_title$0$0({2}DF,SV:S),C,0,0
S:G$engine_content_manager_load_guards$0$0({2}DF,SV:S),C,0,0
S:G$engine_font_manager_draw_char$0$0({2}DF,SV:S),C,0,0
S:G$engine_font_manager_draw_text$0$0({2}DF,SV:S),C,0,0
S:G$engine_font_manager_draw_data$0$0({2}DF,SV:S),C,0,0
S:G$engine_font_manager_draw_data_ZERO$0$0({2}DF,SV:S),C,0,0
S:G$engine_text_manager_clear_all$0$0({2}DF,SV:S),C,0,0
S:G$engine_text_manager_clear_three$0$0({2}DF,SV:S),C,0,0
S:G$engine_text_manager_cheat_blank$0$0({2}DF,SV:S),C,0,0
S:G$engine_text_manager_cheat_write$0$0({2}DF,SV:S),C,0,0
S:G$engine_text_manager_write_gems$0$0({2}DF,SV:S),C,0,0
S:G$engine_text_manager_write_info$0$0({2}DF,SV:S),C,0,0
S:G$engine_delay_manager_load$0$0({2}DF,SV:S),C,0,0
S:G$engine_delay_manager_update$0$0({2}DF,SC:U),C,0,0
S:G$engine_sprite_manager_draw_player$0$0({2}DF,SV:S),C,0,0
S:G$engine_sprite_manager_draw_enemyX$0$0({2}DF,SV:S),C,0,0
S:G$engine_tile_manager_draw_tile$0$0({2}DF,SV:S),C,0,0
S:G$engine_tile_manager_draw_guard$0$0({2}DF,SV:S),C,0,0
S:G$engine_tile_manager_draw_small$0$0({2}DF,SV:S),C,0,0
S:G$engine_tile_manager_draw_tile_side$0$0({2}DF,SV:S),C,0,0
S:G$engine_tile_manager_get_tile$0$0({2}DF,SV:S),C,0,0
S:G$engine_tile_manager_get_collision$0$0({2}DF,SV:S),C,0,0
S:G$engine_tile_manager_get_sprite$0$0({2}DF,SV:S),C,0,0
S:G$engine_input_manager_update$0$0({2}DF,SV:S),C,0,0
S:G$engine_input_manager_hold_up$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_hold_down$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_hold_left$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_hold_right$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_hold_fire1$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_hold_fire2$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_move_up$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_move_down$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_move_left$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_move_right$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_move_fire1$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_move_fire2$0$0({2}DF,SC:U),C,0,0
S:G$engine_anim_manager_player_load_idle$0$0({2}DF,SV:S),C,0,0
S:G$engine_anim_manager_player_load_move$0$0({2}DF,SV:S),C,0,0
S:G$engine_anim_manager_tester_load_anim$0$0({2}DF,SV:S),C,0,0
S:G$engine_anim_manager_enemyX_load_idle$0$0({2}DF,SV:S),C,0,0
S:G$engine_audio_manager_music_game$0$0({2}DF,SV:S),C,0,0
S:G$engine_audio_manager_music_title$0$0({2}DF,SV:S),C,0,0
S:G$engine_audio_manager_music_over$0$0({2}DF,SV:S),C,0,0
S:G$engine_audio_manager_music_beat$0$0({2}DF,SV:S),C,0,0
S:G$engine_audio_manager_music_resume$0$0({2}DF,SV:S),C,0,0
S:G$engine_audio_manager_music_stop$0$0({2}DF,SV:S),C,0,0
S:G$engine_audio_manager_sound_accept$0$0({2}DF,SV:S),C,0,0
S:G$engine_audio_manager_sound_death$0$0({2}DF,SV:S),C,0,0
S:G$engine_audio_manager_sound_gem$0$0({2}DF,SV:S),C,0,0
S:G$engine_audio_manager_sound_level$0$0({2}DF,SV:S),C,0,0
S:G$engine_audio_manager_sound_power$0$0({2}DF,SV:S),C,0,0
S:G$engine_audio_manager_sound_reset$0$0({2}DF,SV:S),C,0,0
S:G$engine_asm_manager_clear_VRAM$0$0({2}DF,SV:S),C,0,0
S:G$atof$0$0({2}DF,SF:S),C,0,0
S:G$atoi$0$0({2}DF,SI:S),C,0,0
S:G$atol$0$0({2}DF,SL:S),C,0,0
S:G$_uitoa$0$0({2}DF,SV:S),C,0,0
S:G$_itoa$0$0({2}DF,SV:S),C,0,0
S:G$_ultoa$0$0({2}DF,SV:S),C,0,0
S:G$_ltoa$0$0({2}DF,SV:S),C,0,0
S:G$rand$0$0({2}DF,SI:S),C,0,0
S:G$srand$0$0({2}DF,SV:S),C,0,0
S:G$calloc$0$0({2}DF,DG,SV:S),C,0,0
S:G$malloc$0$0({2}DF,DG,SV:S),C,0,0
S:G$realloc$0$0({2}DF,DG,SV:S),C,0,0
S:G$free$0$0({2}DF,SV:S),C,0,0
S:G$abs$0$0({2}DF,SI:S),C,0,0
S:G$labs$0$0({2}DF,SL:S),C,0,0
S:G$mblen$0$0({2}DF,SI:S),C,0,0
S:G$mbtowc$0$0({2}DF,SI:S),C,0,0
S:G$wctomb$0$0({2}DF,SI:S),C,0,0
S:G$mbstowcs$0$0({2}DF,SI:U),C,0,0
S:G$wcstombs$0$0({2}DF,SI:U),C,0,0
