M:level_screen
F:G$screen_level_screen_init$0$0({2}DF,SV:S),Z,0,0,0,0,0
F:G$screen_level_screen_load$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Llevel_screen.screen_level_screen_load$go$1$17({2}DG,STtag_struct_game_object:S),R,0,0,[]
F:G$screen_level_screen_update$0$0({2}DF,SV:S),Z,0,6,0,0,0
S:Llevel_screen.screen_level_screen_update$screen_type$1$19({2}DG,SC:U),B,1,4
S:Llevel_screen.screen_level_screen_update$go$1$20({2}DG,STtag_struct_game_object:S),R,0,0,[]
S:Llevel_screen.screen_level_screen_update$test$1$20({6}DA6d,SC:U),B,1,-16
S:Llevel_screen.screen_level_screen_update$delay$1$20({1}SC:U),R,0,0,[c]
S:Llevel_screen.screen_level_screen_update$sloc0$1$0({2}DD,SC:U),B,1,-4
S:Llevel_screen.screen_level_screen_update$sloc1$1$0({2}DD,SC:U),B,1,-8
S:Llevel_screen.screen_level_screen_update$sloc2$1$0({2}DD,SC:U),B,1,-10
S:Llevel_screen.screen_level_screen_update$sloc3$1$0({2}DD,SC:U),B,1,-2
S:Llevel_screen.screen_level_screen_update$sloc4$1$0({2}DD,SC:U),B,1,-6
F:Flevel_screen$display_options$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Llevel_screen.display_options$go$1$42({2}DG,STtag_struct_game_object:S),R,0,0,[]
T:Flevel_screen$tag_struct_game_object[({0}S:S$invincible$0$0({1}SC:U),Z,0,0)({1}S:S$localcheat$0$0({1}SC:U),Z,0,0)({2}S:S$difficulty$0$0({1}SC:U),Z,0,0)({3}S:S$game_speed$0$0({1}SC:U),Z,0,0)({4}S:S$tutorial$0$0({1}SC:U),Z,0,0)({5}S:S$world_no$0$0({1}SC:U),Z,0,0)({6}S:S$round_no$0$0({1}SC:U),Z,0,0)]
T:Flevel_screen$tag_struct_delay_object[({0}S:S$delay_delay$0$0({2}SI:U),Z,0,0)({2}S:S$delay_timer$0$0({2}SI:U),Z,0,0)]
T:Flevel_screen$tag_struct_stats_object[({0}S:S$collision_offsets$0$0({2}DA2d,SC:U),Z,0,0)({2}S:S$enemys_velX$0$0({32}DA4d,DA8d,SC:U),Z,0,0)({34}S:S$enemys_wait$0$0({32}DA4d,DA8d,SC:U),Z,0,0)({66}S:S$enemys_walk$0$0({32}DA4d,DA8d,SC:U),Z,0,0)]
S:Flevel_screen$cursorY$0$0({2}DA2d,SC:U),E,0,0
S:G$count_text$0$0({0}DA0d,DG,SC:U),E,0,0
S:G$lives_text$0$0({0}DA0d,DG,SC:U),E,0,0
S:G$global_delay_object$0$0({4}STtag_struct_delay_object:S),E,0,0
S:G$global_stats_object$0$0({98}STtag_struct_stats_object:S),E,0,0
S:G$global_game_object$0$0({7}STtag_struct_game_object:S),E,0,0
S:Flevel_screen$stage$0$0({1}SC:U),E,0,0
S:Flevel_screen$cursor$0$0({1}SC:U),E,0,0
S:G$engine_content_manager_load_back_tiles$0$0({2}DF,SV:S),C,0,0
S:G$engine_content_manager_load_sprites$0$0({2}DF,SV:S),C,0,0
S:G$engine_content_manager_load_splash$0$0({2}DF,SV:S),C,0,0
S:G$engine_content_manager_load_title$0$0({2}DF,SV:S),C,0,0
S:G$engine_content_manager_load_guards$0$0({2}DF,SV:S),C,0,0
S:G$engine_font_manager_draw_char$0$0({2}DF,SV:S),C,0,0
S:G$engine_font_manager_draw_text$0$0({2}DF,SV:S),C,0,0
S:G$engine_font_manager_draw_data$0$0({2}DF,SV:S),C,0,0
S:G$engine_font_manager_draw_data_ZERO$0$0({2}DF,SV:S),C,0,0
S:G$engine_text_manager_clear_all$0$0({2}DF,SV:S),C,0,0
S:G$engine_text_manager_clear_three$0$0({2}DF,SV:S),C,0,0
S:G$engine_text_manager_cheat_blank$0$0({2}DF,SV:S),C,0,0
S:G$engine_text_manager_cheat_write$0$0({2}DF,SV:S),C,0,0
S:G$engine_text_manager_write_gems$0$0({2}DF,SV:S),C,0,0
S:G$engine_text_manager_write_info$0$0({2}DF,SV:S),C,0,0
S:G$engine_tile_manager_draw_tile$0$0({2}DF,SV:S),C,0,0
S:G$engine_tile_manager_draw_guard$0$0({2}DF,SV:S),C,0,0
S:G$engine_tile_manager_draw_small$0$0({2}DF,SV:S),C,0,0
S:G$engine_tile_manager_draw_tile_side$0$0({2}DF,SV:S),C,0,0
S:G$engine_tile_manager_get_tile$0$0({2}DF,SV:S),C,0,0
S:G$engine_tile_manager_get_collision$0$0({2}DF,SV:S),C,0,0
S:G$engine_tile_manager_get_sprite$0$0({2}DF,SV:S),C,0,0
S:G$engine_delay_manager_load$0$0({2}DF,SV:S),C,0,0
S:G$engine_delay_manager_update$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_update$0$0({2}DF,SV:S),C,0,0
S:G$engine_input_manager_hold_up$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_hold_down$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_hold_left$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_hold_right$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_hold_fire1$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_hold_fire2$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_move_up$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_move_down$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_move_left$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_move_right$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_move_fire1$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_move_fire2$0$0({2}DF,SC:U),C,0,0
S:G$engine_stats_manager_init$0$0({2}DF,SV:S),C,0,0
S:G$engine_audio_manager_music_game$0$0({2}DF,SV:S),C,0,0
S:G$engine_audio_manager_music_title$0$0({2}DF,SV:S),C,0,0
S:G$engine_audio_manager_music_over$0$0({2}DF,SV:S),C,0,0
S:G$engine_audio_manager_music_beat$0$0({2}DF,SV:S),C,0,0
S:G$engine_audio_manager_music_resume$0$0({2}DF,SV:S),C,0,0
S:G$engine_audio_manager_music_stop$0$0({2}DF,SV:S),C,0,0
S:G$engine_audio_manager_sound_accept$0$0({2}DF,SV:S),C,0,0
S:G$engine_audio_manager_sound_death$0$0({2}DF,SV:S),C,0,0
S:G$engine_audio_manager_sound_gem$0$0({2}DF,SV:S),C,0,0
S:G$engine_audio_manager_sound_level$0$0({2}DF,SV:S),C,0,0
S:G$engine_audio_manager_sound_power$0$0({2}DF,SV:S),C,0,0
S:G$engine_audio_manager_sound_reset$0$0({2}DF,SV:S),C,0,0
S:G$engine_game_manager_init$0$0({2}DF,SV:S),C,0,0
S:G$engine_game_manager_draw$0$0({2}DF,SV:S),C,0,0
