M:reset_manager
F:G$engine_reset_manager_load$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lreset_manager.engine_reset_manager_load$frame$1$6({1}SC:U),B,1,4
S:Lreset_manager.engine_reset_manager_load$ro$1$7({2}DG,STtag_struct_reset_object:S),R,0,0,[]
F:G$engine_reset_manager_reset$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lreset_manager.engine_reset_manager_reset$ro$1$8({2}DG,STtag_struct_reset_object:S),R,0,0,[]
F:G$engine_reset_manager_update$0$0({2}DF,SC:U),Z,0,0,0,0,0
S:Lreset_manager.engine_reset_manager_update$ro$1$9({2}DG,STtag_struct_reset_object:S),R,0,0,[]
S:Lreset_manager.engine_reset_manager_update$test$1$9({1}SC:U),R,0,0,[d]
T:Freset_manager$tag_struct_reset_object[({0}S:S$reset_frame$0$0({1}SC:U),Z,0,0)({1}S:S$reset_timer$0$0({1}SC:U),Z,0,0)({2}S:S$reset_screen$0$0({1}SC:U),Z,0,0)]
S:G$global_reset_object$0$0({3}STtag_struct_reset_object:S),E,0,0
S:G$engine_font_manager_draw_char$0$0({2}DF,SV:S),C,0,0
S:G$engine_font_manager_draw_text$0$0({2}DF,SV:S),C,0,0
S:G$engine_font_manager_draw_data$0$0({2}DF,SV:S),C,0,0
S:G$engine_font_manager_draw_data_ZERO$0$0({2}DF,SV:S),C,0,0
