M:score_manager
F:G$engine_score_manager_init$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lscore_manager.engine_score_manager_init$difficulty$1$15({1}SC:U),B,1,4
S:Lscore_manager.engine_score_manager_init$so$1$16({2}DG,STtag_struct_score_object:S),R,0,0,[]
F:G$engine_score_manager_reset_gems$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lscore_manager.engine_score_manager_reset_gems$so$1$17({2}DG,STtag_struct_score_object:S),R,0,0,[]
F:G$engine_score_manager_reset_lives$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lscore_manager.engine_score_manager_reset_lives$so$1$18({2}DG,STtag_struct_score_object:S),R,0,0,[]
F:G$engine_score_manager_update_gems$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lscore_manager.engine_score_manager_update_gems$so$1$19({2}DG,STtag_struct_score_object:S),R,0,0,[]
F:G$engine_score_manager_bonus_gems$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lscore_manager.engine_score_manager_bonus_gems$so$1$21({2}DG,STtag_struct_score_object:S),R,0,0,[]
F:G$engine_score_manager_update_lives$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lscore_manager.engine_score_manager_update_lives$delta$1$23({1}SC:S),B,1,4
S:Lscore_manager.engine_score_manager_update_lives$so$1$24({2}DG,STtag_struct_score_object:S),R,0,0,[]
F:G$engine_score_manager_draw_lives$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lscore_manager.engine_score_manager_draw_lives$so$1$26({2}DG,STtag_struct_score_object:S),R,0,0,[]
S:Lscore_manager.engine_score_manager_draw_lives$index$1$26({1}SC:U),R,0,0,[e]
F:G$engine_score_manager_draw_score$0$0({2}DF,SV:S),Z,0,0,0,0,0
F:G$engine_score_manager_draw_score_at$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lscore_manager.engine_score_manager_draw_score_at$x$1$28({1}SC:U),B,1,4
S:Lscore_manager.engine_score_manager_draw_score_at$y$1$28({1}SC:U),B,1,5
S:Lscore_manager.engine_score_manager_draw_score_at$so$1$29({2}DG,STtag_struct_score_object:S),R,0,0,[]
T:Fscore_manager$tag_struct_score_object[({0}S:S$tot_lives$0$0({1}SC:U),Z,0,0)({1}S:S$num_lives$0$0({1}SC:U),Z,0,0)({2}S:S$gem_count$0$0({1}SC:U),Z,0,0)({3}S:S$gem_level$0$0({1}SC:U),Z,0,0)({4}S:S$gem_total$0$0({2}SI:U),Z,0,0)]
S:G$count_text$0$0({0}DA0d,DG,SC:U),E,0,0
S:G$lives_text$0$0({0}DA0d,DG,SC:U),E,0,0
S:G$global_score_object$0$0({6}STtag_struct_score_object:S),E,0,0
S:G$engine_font_manager_draw_char$0$0({2}DF,SV:S),C,0,0
S:G$engine_font_manager_draw_text$0$0({2}DF,SV:S),C,0,0
S:G$engine_font_manager_draw_data$0$0({2}DF,SV:S),C,0,0
S:G$engine_font_manager_draw_data_ZERO$0$0({2}DF,SV:S),C,0,0
S:G$engine_tile_manager_draw_tile$0$0({2}DF,SV:S),C,0,0
S:G$engine_tile_manager_draw_guard$0$0({2}DF,SV:S),C,0,0
S:G$engine_tile_manager_draw_small$0$0({2}DF,SV:S),C,0,0
S:G$engine_tile_manager_draw_tile_side$0$0({2}DF,SV:S),C,0,0
S:G$engine_tile_manager_get_tile$0$0({2}DF,SV:S),C,0,0
S:G$engine_tile_manager_get_collision$0$0({2}DF,SV:S),C,0,0
S:G$engine_tile_manager_get_sprite$0$0({2}DF,SV:S),C,0,0
