M:test_screen
F:G$screen_test_screen_load$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Ltest_screen.screen_test_screen_load$status$1$25({1}SC:U),R,0,0,[c]
F:G$screen_test_screen_update$0$0({2}DF,SV:S),Z,0,4,0,0,0
S:Ltest_screen.screen_test_screen_update$screen_type$1$26({2}DG,SC:U),B,1,4
S:Ltest_screen.screen_test_screen_update$test$1$27({4}DA4d,SC:U),B,1,-8
S:Ltest_screen.screen_test_screen_update$status$1$27({1}SC:U),R,0,0,[l]
S:Ltest_screen.screen_test_screen_update$sloc0$1$0({2}DD,SC:U),B,1,-2
S:Ltest_screen.screen_test_screen_update$sloc1$1$0({2}DD,SC:U),B,1,-4
S:G$count_text$0$0({0}DA0d,DG,SC:U),E,0,0
S:G$lives_text$0$0({0}DA0d,DG,SC:U),E,0,0
S:G$devkit_PSGPlay$0$0({2}DF,SV:S),C,0,0
S:G$devkit_PSGCancelLoop$0$0({2}DF,SV:S),C,0,0
S:G$devkit_PSGPlayNoRepeat$0$0({2}DF,SV:S),C,0,0
S:G$devkit_PSGStop$0$0({2}DF,SV:S),C,0,0
S:G$devkit_PSGResume$0$0({2}DF,SV:S),C,0,0
S:G$PSGGetStatus$0$0({2}DF,SC:U),C,0,0
S:G$devkit_PSGSetMusicVolumeAttenuation$0$0({2}DF,SV:S),C,0,0
S:G$devkit_PSGSFXPlay$0$0({2}DF,SV:S),C,0,0
S:G$devkit_PSGSFXPlayLoop$0$0({2}DF,SV:S),C,0,0
S:G$devkit_PSGSFXCancelLoop$0$0({2}DF,SV:S),C,0,0
S:G$devkit_PSGSFXStop$0$0({2}DF,SV:S),C,0,0
S:G$devkit_PSGSFXGetStatus$0$0({2}DF,SC:U),C,0,0
S:G$devkit_PSGSilenceChannels$0$0({2}DF,SV:S),C,0,0
S:G$devkit_PSGRestoreVolumes$0$0({2}DF,SV:S),C,0,0
S:G$devkit_PSGFrame$0$0({2}DF,SV:S),C,0,0
S:G$devkit_PSGSFXFrame$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SFX_CHANNEL2$0$0({2}DF,SC:U),C,0,0
S:G$devkit_SFX_CHANNEL3$0$0({2}DF,SC:U),C,0,0
S:G$devkit_SFX_CHANNELS2AND3$0$0({2}DF,SC:U),C,0,0
S:G$engine_font_manager_draw_char$0$0({2}DF,SV:S),C,0,0
S:G$engine_font_manager_draw_text$0$0({2}DF,SV:S),C,0,0
S:G$engine_font_manager_draw_data$0$0({2}DF,SV:S),C,0,0
S:G$engine_font_manager_draw_data_ZERO$0$0({2}DF,SV:S),C,0,0
S:G$engine_memo_manager_init$0$0({2}DF,SV:S),C,0,0
S:G$engine_memo_manager_draw_title$0$0({2}DF,SV:S),C,0,0
S:G$engine_memo_manager_draw_level$0$0({2}DF,SV:S),C,0,0
S:G$engine_memo_manager_draw_reset$0$0({2}DF,SV:S),C,0,0
S:G$engine_memo_manager_draw_pass$0$0({2}DF,SV:S),C,0,0
S:G$engine_memo_manager_draw_gems$0$0({2}DF,SV:S),C,0,0
S:G$engine_memo_manager_draw_dead$0$0({2}DF,SV:S),C,0,0
S:G$engine_memo_manager_draw_cont$0$0({2}DF,SV:S),C,0,0
S:G$engine_memo_manager_draw_over$0$0({2}DF,SV:S),C,0,0
S:G$engine_memo_manager_draw_beat$0$0({2}DF,SV:S),C,0,0
S:G$engine_input_manager_update$0$0({2}DF,SV:S),C,0,0
S:G$engine_input_manager_hold_up$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_hold_down$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_hold_left$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_hold_right$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_hold_fire1$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_hold_fire2$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_move_up$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_move_down$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_move_left$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_move_right$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_move_fire1$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_move_fire2$0$0({2}DF,SC:U),C,0,0
S:G$engine_audio_manager_music_game$0$0({2}DF,SV:S),C,0,0
S:G$engine_audio_manager_music_title$0$0({2}DF,SV:S),C,0,0
S:G$engine_audio_manager_music_over$0$0({2}DF,SV:S),C,0,0
S:G$engine_audio_manager_music_beat$0$0({2}DF,SV:S),C,0,0
S:G$engine_audio_manager_music_resume$0$0({2}DF,SV:S),C,0,0
S:G$engine_audio_manager_music_stop$0$0({2}DF,SV:S),C,0,0
S:G$engine_audio_manager_sound_accept$0$0({2}DF,SV:S),C,0,0
S:G$engine_audio_manager_sound_death$0$0({2}DF,SV:S),C,0,0
S:G$engine_audio_manager_sound_gem$0$0({2}DF,SV:S),C,0,0
S:G$engine_audio_manager_sound_level$0$0({2}DF,SV:S),C,0,0
S:G$engine_audio_manager_sound_power$0$0({2}DF,SV:S),C,0,0
S:G$engine_audio_manager_sound_reset$0$0({2}DF,SV:S),C,0,0
