M:gamer_manager
F:G$engine_gamer_manager_init$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lgamer_manager.engine_gamer_manager_init$px$1$17({1}SC:U),B,1,4
S:Lgamer_manager.engine_gamer_manager_init$py$1$17({1}SC:U),B,1,5
S:Lgamer_manager.engine_gamer_manager_init$vel$1$17({1}SC:U),B,1,6
S:Lgamer_manager.engine_gamer_manager_init$tile$1$17({2}SI:U),B,1,7
S:Lgamer_manager.engine_gamer_manager_init$go$1$18({2}DG,STtag_struct_gamer_object:S),R,0,0,[c,b]
F:G$engine_gamer_manager_update$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lgamer_manager.engine_gamer_manager_update$dx$1$19({1}SC:U),B,1,4
S:Lgamer_manager.engine_gamer_manager_update$dy$1$19({1}SC:U),B,1,5
S:Lgamer_manager.engine_gamer_manager_update$go$1$20({2}DG,STtag_struct_gamer_object:S),R,0,0,[e,d]
F:G$engine_gamer_manager_draw$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lgamer_manager.engine_gamer_manager_draw$go$1$21({2}DG,STtag_struct_gamer_object:S),R,0,0,[]
T:Fgamer_manager$tag_struct_gamer_object[({0}S:S$gamerX$0$0({1}SC:U),Z,0,0)({1}S:S$gamerY$0$0({1}SC:U),Z,0,0)({2}S:S$velocity$0$0({1}SC:U),Z,0,0)({3}S:S$tile$0$0({2}SI:U),Z,0,0)]
S:G$global_gamer_object$0$0({5}STtag_struct_gamer_object:S),E,0,0
S:G$devkit_SMS_init$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_displayOn$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_displayOff$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_mapROMBank$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_enableSRAM$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_enableSRAMBank$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_disableSRAM$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_SRAM$0$0({2}DF,DG,SC:U),C,0,0
S:G$devkit_SMS_setSpriteMode$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_useFirstHalfTilesforSprites_False$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_useFirstHalfTilesforSprites_True$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_VDPturnOnFeature$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadPSGaidencompressedTiles$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadSTMcompressedTileMap$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadBGPalette$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadSpritePalette$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setSpritePaletteColor$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setNextTileatXY$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setTile$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setTilePriority$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_addSprite$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_initSprites$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_finalizeSprites$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_waitForVBlank$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_copySpritestoSAT$0$0({2}DF,SV:S),C,0,0
S:G$devkit_UNSAFE_SMS_copySpritestoSAT$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_queryPauseRequested$0$0({2}DF,SC:U),C,0,0
S:G$devkit_SMS_resetPauseRequest$0$0({2}DF,SV:S),C,0,0
S:G$devkit_isCollisionDetected$0$0({2}DF,SC:U),C,0,0
S:G$devkit_SMS_getKeysStatus$0$0({2}DF,SI:U),C,0,0
S:G$devkit_SPRITEMODE_NORMAL$0$0({2}DF,SC:U),C,0,0
S:G$devkit_VDPFEATURE_HIDEFIRSTCOL$0$0({2}DF,SI:U),C,0,0
S:G$devkit_TILE_PRIORITY$0$0({2}DF,SI:U),C,0,0
S:G$devkit_TILE_USE_SPRITE_PALETTE$0$0({2}DF,SI:U),C,0,0
S:G$engine_sprite_manager_draw$0$0({2}DF,SV:S),C,0,0
