M:screen_manager
F:G$engine_screen_manager_init$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lscreen_manager.engine_screen_manager_init$index$1$6({1}SC:U),R,0,0,[c]
F:G$engine_screen_manager_update$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lscreen_manager.engine_screen_manager_update$input$1$9({1}SC:U),R,0,0,[c]
S:Lscreen_manager.engine_screen_manager_update$delta$1$9({2}SI:U),R,0,0,[c,b]
S:Fscreen_manager$ascent$0$0({34}DA17d,SI:U),E,0,0
S:Fscreen_manager$descent$0$0({16}DA8d,SI:U),E,0,0
S:Fscreen_manager$topBlock$0$0({2}SI:U),E,0,0
S:Fscreen_manager$platform$0$0({1}SC:U),E,0,0
S:Fscreen_manager$enemy_y$0$0({1}SC:U),E,0,0
S:Fscreen_manager$cur_value_y$0$0({2}SI:U),E,0,0
S:Fscreen_manager$value_y$0$0({2}SI:U),E,0,0
S:Fscreen_manager$index$0$0({1}SC:U),E,0,0
S:Fscreen_manager$count$0$0({1}SC:U),E,0,0
S:Fscreen_manager$state$0$0({1}SC:U),E,0,0
S:G$engine_music_manager_play$0$0({2}DF,SV:S),C,0,0
S:G$engine_sound_manager_play$0$0({2}DF,SV:S),C,0,0
S:G$engine_content_manager_load_tiles$0$0({2}DF,SV:S),C,0,0
S:G$engine_content_manager_load_turtle$0$0({2}DF,SV:S),C,0,0
S:G$engine_font_manager_draw_char$0$0({2}DF,SV:S),C,0,0
S:G$engine_font_manager_draw_text$0$0({2}DF,SV:S),C,0,0
S:G$engine_font_manager_draw_data$0$0({2}DF,SV:S),C,0,0
S:G$engine_font_manager_draw_zero$0$0({2}DF,SV:S),C,0,0
S:G$engine_input_manager_update$0$0({2}DF,SV:S),C,0,0
S:G$engine_input_manager_hold_up$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_hold_down$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_hold_left$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_hold_right$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_hold_fire1$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_hold_fire2$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_move_up$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_move_down$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_move_left$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_move_right$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_move_fire1$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_move_fire2$0$0({2}DF,SC:U),C,0,0
S:G$engine_sprite_manager_draw$0$0({2}DF,SV:S),C,0,0
