M:level_manager
F:G$engine_level_manager_init$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Llevel_manager.engine_level_manager_init$lo$1$15({2}DG,STtag_struct_level_object:S),R,0,0,[c,b]
F:G$engine_level_manager_update$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Llevel_manager.engine_level_manager_update$column_X$1$16({1}SC:U),B,1,4
S:Llevel_manager.engine_level_manager_update$scroll_X$1$16({2}SI:U),B,1,5
S:Llevel_manager.engine_level_manager_update$lo$1$17({2}DG,STtag_struct_level_object:S),R,0,0,[]
S:Llevel_manager.engine_level_manager_update$index$1$17({1}SC:U),R,0,0,[]
S:Llevel_manager.engine_level_manager_update$four$1$17({1}SC:U),R,0,0,[d]
S:Llevel_manager.engine_level_manager_update$column_Y$1$17({1}SC:U),R,0,0,[]
S:Llevel_manager.engine_level_manager_update$level_column$1$17({2}SI:U),R,0,0,[]
S:Llevel_manager.engine_level_manager_update$level_object$1$17({1}SC:U),R,0,0,[]
S:Llevel_manager.engine_level_manager_update$level_metadata$1$17({1}SC:U),R,0,0,[]
T:Flevel_manager$tag_struct_level_object[({0}S:S$level_index$0$0({1}SC:U),Z,0,0)({1}S:S$planeA_type$0$0({1}SC:U),Z,0,0)({2}S:S$planeB_type$0$0({1}SC:U),Z,0,0)]
S:G$global_level_object$0$0({3}STtag_struct_level_object:S),E,0,0
S:G$engine_tile_manager_sky$0$0({2}DF,SV:S),C,0,0
S:G$engine_tile_manager_sea$0$0({2}DF,SV:S),C,0,0
S:G$engine_tile_manager_blank_column$0$0({2}DF,SV:S),C,0,0
S:G$engine_tile_manager_draw_pipe$0$0({2}DF,SV:S),C,0,0
S:G$engine_tile_manager_draw_tile$0$0({2}DF,SV:S),C,0,0
S:G$engine_tile_manager_draw_norm$0$0({2}DF,SV:S),C,0,0
S:G$engine_tile_manager_draw_flip$0$0({2}DF,SV:S),C,0,0
S:G$engine_tile_manager_draw_offset$0$0({2}DF,SV:S),C,0,0
S:G$engine_tile_manager_sea_turtle$0$0({2}DF,SV:S),C,0,0
S:G$engine_tile_manager_fly_turtle$0$0({2}DF,SV:S),C,0,0
S:G$engine_tile_manager_section03$0$0({2}DF,SV:S),C,0,0
S:G$engine_tile_manager_sign$0$0({2}DF,SV:S),C,0,0
S:G$engine_tile_manager_draw_flip2$0$0({2}DF,SV:S),C,0,0
S:G$engine_tile_manager_draw_norm2$0$0({2}DF,SV:S),C,0,0
S:G$engine_tile_manager_draw_offset2$0$0({2}DF,SV:S),C,0,0
