M:tile_manager
F:G$engine_tile_manager_blank_column$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Ltile_manager.engine_tile_manager_blank_column$column_X$1$78({1}SC:U),B,1,4
S:Ltile_manager.engine_tile_manager_blank_column$column_Y$1$78({1}SC:U),B,1,5
S:Ltile_manager.engine_tile_manager_blank_column$tiles$1$79({2}DG,SC:U),R,0,0,[]
S:Ltile_manager.engine_tile_manager_blank_column$row$1$79({1}SC:U),R,0,0,[d]
S:Ltile_manager.engine_tile_manager_blank_column$src$1$79({2}DG,SV:S),R,0,0,[c,b]
F:G$engine_tile_manager_draw_pipe$0$0({2}DF,SV:S),Z,0,3,0,0,0
S:Ltile_manager.engine_tile_manager_draw_pipe$type$1$82({1}SC:U),B,1,4
S:Ltile_manager.engine_tile_manager_draw_pipe$x$1$82({2}SI:U),B,1,5
S:Ltile_manager.engine_tile_manager_draw_pipe$y$1$82({1}SC:U),B,1,7
S:Ltile_manager.engine_tile_manager_draw_pipe$col$1$82({1}SC:U),B,1,8
S:Ltile_manager.engine_tile_manager_draw_pipe$tiles$1$83({2}DG,SC:U),R,0,0,[]
S:Ltile_manager.engine_tile_manager_draw_pipe$array$1$83({2}DG,SC:U),R,0,0,[c,b]
S:Ltile_manager.engine_tile_manager_draw_pipe$wide$1$83({1}SC:U),B,1,-5
S:Ltile_manager.engine_tile_manager_draw_pipe$high$1$83({1}SC:U),B,1,-4
S:Ltile_manager.engine_tile_manager_draw_pipe$idx$1$83({1}SC:U),R,0,0,[e]
S:Ltile_manager.engine_tile_manager_draw_pipe$val$1$83({1}SC:U),R,0,0,[l]
S:Ltile_manager.engine_tile_manager_draw_pipe$off$1$83({2}SI:U),R,0,0,[l,h]
S:Ltile_manager.engine_tile_manager_draw_pipe$row$1$83({1}SC:U),B,1,-3
S:Ltile_manager.engine_tile_manager_draw_pipe$sloc0$1$0({2}DG,SV:S),B,1,-2
F:G$engine_tile_manager_draw_norm2$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Ltile_manager.engine_tile_manager_draw_norm2$type$1$86({1}SC:U),B,1,4
S:Ltile_manager.engine_tile_manager_draw_norm2$x$1$86({1}SC:U),B,1,5
S:Ltile_manager.engine_tile_manager_draw_norm2$y$1$86({1}SC:U),B,1,6
F:G$engine_tile_manager_draw_offset2$0$0({2}DF,SV:S),Z,0,7,0,0,0
S:Ltile_manager.engine_tile_manager_draw_offset2$type$1$88({1}SC:U),B,1,4
S:Ltile_manager.engine_tile_manager_draw_offset2$offset$1$88({1}SC:U),B,1,5
S:Ltile_manager.engine_tile_manager_draw_offset2$x$1$88({1}SC:U),B,1,6
S:Ltile_manager.engine_tile_manager_draw_offset2$y$1$88({1}SC:U),B,1,7
S:Ltile_manager.engine_tile_manager_draw_offset2$tiles$1$89({2}DG,SC:U),R,0,0,[]
S:Ltile_manager.engine_tile_manager_draw_offset2$array$1$89({2}DG,SC:U),B,1,-7
S:Ltile_manager.engine_tile_manager_draw_offset2$wide$1$89({1}SC:U),B,1,-3
S:Ltile_manager.engine_tile_manager_draw_offset2$high$1$89({1}SC:U),B,1,-8
S:Ltile_manager.engine_tile_manager_draw_offset2$idx$1$89({1}SC:U),R,0,0,[e]
S:Ltile_manager.engine_tile_manager_draw_offset2$val$1$89({1}SC:U),R,0,0,[b]
S:Ltile_manager.engine_tile_manager_draw_offset2$row$1$89({1}SC:U),B,1,-4
S:Ltile_manager.engine_tile_manager_draw_offset2$col$1$89({1}SC:U),R,0,0,[c]
S:Ltile_manager.engine_tile_manager_draw_offset2$spc$1$89({1}SC:U),B,1,-5
S:Ltile_manager.engine_tile_manager_draw_offset2$tmp$1$89({1}SC:U),B,1,-9
S:Ltile_manager.engine_tile_manager_draw_offset2$sloc0$1$0({1}SC:U),B,1,-2
S:Ltile_manager.engine_tile_manager_draw_offset2$sloc1$1$0({1}SC:U),B,1,-1
F:G$engine_tile_manager_draw_norm$0$0({2}DF,SV:S),Z,0,2,0,0,0
S:Ltile_manager.engine_tile_manager_draw_norm$type$1$94({1}SC:U),B,1,4
S:Ltile_manager.engine_tile_manager_draw_norm$x$1$94({1}SC:U),B,1,5
S:Ltile_manager.engine_tile_manager_draw_norm$y$1$94({1}SC:U),B,1,6
S:Ltile_manager.engine_tile_manager_draw_norm$wide$1$94({1}SC:U),B,1,7
S:Ltile_manager.engine_tile_manager_draw_norm$high$1$94({1}SC:U),B,1,8
S:Ltile_manager.engine_tile_manager_draw_norm$beg$1$94({1}SC:U),B,1,9
S:Ltile_manager.engine_tile_manager_draw_norm$end$1$94({1}SC:U),B,1,10
S:Ltile_manager.engine_tile_manager_draw_norm$tiles$1$95({2}DG,SC:U),R,0,0,[]
S:Ltile_manager.engine_tile_manager_draw_norm$array$1$95({2}DG,SC:U),B,1,-5
S:Ltile_manager.engine_tile_manager_draw_norm$idx$1$95({1}SC:U),R,0,0,[e]
S:Ltile_manager.engine_tile_manager_draw_norm$val$1$95({1}SC:U),R,0,0,[e]
S:Ltile_manager.engine_tile_manager_draw_norm$row$1$95({1}SC:U),R,0,0,[c]
S:Ltile_manager.engine_tile_manager_draw_norm$col$1$95({1}SC:U),R,0,0,[]
S:Ltile_manager.engine_tile_manager_draw_norm$spc$1$95({1}SC:U),R,0,0,[b]
S:Ltile_manager.engine_tile_manager_draw_norm$sloc0$1$0({1}SC:U),B,1,-2
S:Ltile_manager.engine_tile_manager_draw_norm$sloc1$1$0({1}SC:U),B,1,-3
S:Ltile_manager.engine_tile_manager_draw_norm$sloc2$1$0({1}SC:U),B,1,-1
F:G$engine_tile_manager_draw_offset$0$0({2}DF,SV:S),Z,0,3,0,0,0
S:Ltile_manager.engine_tile_manager_draw_offset$type$1$100({1}SC:U),B,1,4
S:Ltile_manager.engine_tile_manager_draw_offset$x$1$100({1}SC:U),B,1,5
S:Ltile_manager.engine_tile_manager_draw_offset$y$1$100({1}SC:U),B,1,6
S:Ltile_manager.engine_tile_manager_draw_offset$wide$1$100({1}SC:U),B,1,7
S:Ltile_manager.engine_tile_manager_draw_offset$high$1$100({1}SC:U),B,1,8
S:Ltile_manager.engine_tile_manager_draw_offset$beg$1$100({1}SC:U),B,1,9
S:Ltile_manager.engine_tile_manager_draw_offset$end$1$100({1}SC:U),B,1,10
S:Ltile_manager.engine_tile_manager_draw_offset$off$1$100({1}SC:U),B,1,11
S:Ltile_manager.engine_tile_manager_draw_offset$tiles$1$101({2}DG,SC:U),R,0,0,[]
S:Ltile_manager.engine_tile_manager_draw_offset$array$1$101({2}DG,SC:U),B,1,-5
S:Ltile_manager.engine_tile_manager_draw_offset$idx$1$101({1}SC:U),R,0,0,[c]
S:Ltile_manager.engine_tile_manager_draw_offset$val$1$101({1}SC:U),R,0,0,[c]
S:Ltile_manager.engine_tile_manager_draw_offset$row$1$101({1}SC:U),R,0,0,[e]
S:Ltile_manager.engine_tile_manager_draw_offset$col$1$101({1}SC:U),R,0,0,[]
S:Ltile_manager.engine_tile_manager_draw_offset$spc$1$101({1}SC:U),R,0,0,[d]
S:Ltile_manager.engine_tile_manager_draw_offset$tmp$1$101({1}SC:U),B,1,-6
S:Ltile_manager.engine_tile_manager_draw_offset$sloc0$1$0({1}SC:U),B,1,-1
S:Ltile_manager.engine_tile_manager_draw_offset$sloc1$1$0({1}SC:U),B,1,-2
S:Ltile_manager.engine_tile_manager_draw_offset$sloc2$1$0({1}SC:U),B,1,-3
F:G$engine_tile_manager_draw_flip2$0$0({2}DF,SV:S),Z,0,8,0,0,0
S:Ltile_manager.engine_tile_manager_draw_flip2$type$1$106({1}SC:U),B,1,4
S:Ltile_manager.engine_tile_manager_draw_flip2$x$1$106({1}SC:U),B,1,5
S:Ltile_manager.engine_tile_manager_draw_flip2$y$1$106({1}SC:U),B,1,6
S:Ltile_manager.engine_tile_manager_draw_flip2$tiles$1$107({2}DG,SC:U),R,0,0,[]
S:Ltile_manager.engine_tile_manager_draw_flip2$array$1$107({2}DG,SC:U),B,1,-7
S:Ltile_manager.engine_tile_manager_draw_flip2$wide$1$107({1}SC:U),B,1,-4
S:Ltile_manager.engine_tile_manager_draw_flip2$high$1$107({1}SC:U),B,1,-3
S:Ltile_manager.engine_tile_manager_draw_flip2$idx$1$107({1}SC:U),R,0,0,[e]
S:Ltile_manager.engine_tile_manager_draw_flip2$val$1$107({1}SC:U),R,0,0,[b]
S:Ltile_manager.engine_tile_manager_draw_flip2$row$1$107({1}SC:U),B,1,-10
S:Ltile_manager.engine_tile_manager_draw_flip2$col$1$107({1}SC:U),R,0,0,[b]
S:Ltile_manager.engine_tile_manager_draw_flip2$spc$1$107({1}SC:U),B,1,-5
S:Ltile_manager.engine_tile_manager_draw_flip2$tmp$1$107({1}SC:U),R,0,0,[c]
S:Ltile_manager.engine_tile_manager_draw_flip2$flip$1$107({2}SI:U),B,1,-9
S:Ltile_manager.engine_tile_manager_draw_flip2$sloc0$1$0({1}SC:U),B,1,-1
S:Ltile_manager.engine_tile_manager_draw_flip2$sloc1$1$0({1}SC:U),B,1,-2
F:G$engine_tile_manager_draw_flip$0$0({2}DF,SV:S),Z,0,4,0,0,0
S:Ltile_manager.engine_tile_manager_draw_flip$type$1$112({1}SC:U),B,1,4
S:Ltile_manager.engine_tile_manager_draw_flip$x$1$112({1}SC:U),B,1,5
S:Ltile_manager.engine_tile_manager_draw_flip$y$1$112({1}SC:U),B,1,6
S:Ltile_manager.engine_tile_manager_draw_flip$wide$1$112({1}SC:U),B,1,7
S:Ltile_manager.engine_tile_manager_draw_flip$high$1$112({1}SC:U),B,1,8
S:Ltile_manager.engine_tile_manager_draw_flip$beg$1$112({1}SC:U),B,1,9
S:Ltile_manager.engine_tile_manager_draw_flip$end$1$112({1}SC:U),B,1,10
S:Ltile_manager.engine_tile_manager_draw_flip$tiles$1$113({2}DG,SC:U),R,0,0,[]
S:Ltile_manager.engine_tile_manager_draw_flip$array$1$113({2}DG,SC:U),B,1,-7
S:Ltile_manager.engine_tile_manager_draw_flip$idx$1$113({1}SC:U),R,0,0,[e]
S:Ltile_manager.engine_tile_manager_draw_flip$val$1$113({1}SC:U),R,0,0,[e]
S:Ltile_manager.engine_tile_manager_draw_flip$row$1$113({1}SC:U),R,0,0,[c]
S:Ltile_manager.engine_tile_manager_draw_flip$col$1$113({1}SC:U),R,0,0,[e]
S:Ltile_manager.engine_tile_manager_draw_flip$spc$1$113({1}SC:U),R,0,0,[b]
S:Ltile_manager.engine_tile_manager_draw_flip$tmp$1$113({1}SC:U),R,0,0,[]
S:Ltile_manager.engine_tile_manager_draw_flip$flip$1$113({2}SI:U),B,1,-5
S:Ltile_manager.engine_tile_manager_draw_flip$sloc0$1$0({1}SC:U),B,1,-2
S:Ltile_manager.engine_tile_manager_draw_flip$sloc1$1$0({1}SC:U),B,1,-3
S:Ltile_manager.engine_tile_manager_draw_flip$sloc2$1$0({1}SC:U),B,1,-1
F:G$engine_tile_manager_draw_tile$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Ltile_manager.engine_tile_manager_draw_tile$type$1$118({1}SC:U),B,1,4
S:Ltile_manager.engine_tile_manager_draw_tile$x$1$118({1}SC:U),B,1,5
S:Ltile_manager.engine_tile_manager_draw_tile$y$1$118({1}SC:U),B,1,6
S:Ltile_manager.engine_tile_manager_draw_tile$wide$1$119({1}SC:U),R,0,0,[b]
S:Ltile_manager.engine_tile_manager_draw_tile$high$1$119({1}SC:U),R,0,0,[d]
F:G$engine_tile_manager_sea_turtle$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Ltile_manager.engine_tile_manager_sea_turtle$turtle$1$120({1}SC:U),B,1,4
S:Ltile_manager.engine_tile_manager_sea_turtle$x$1$120({1}SC:U),B,1,5
S:Ltile_manager.engine_tile_manager_sea_turtle$y$1$120({1}SC:U),B,1,6
F:G$engine_tile_manager_fly_turtle$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Ltile_manager.engine_tile_manager_fly_turtle$turtle$1$122({1}SC:U),B,1,4
S:Ltile_manager.engine_tile_manager_fly_turtle$x$1$122({1}SC:U),B,1,5
S:Ltile_manager.engine_tile_manager_fly_turtle$y$1$122({1}SC:U),B,1,6
F:G$engine_tile_manager_sign$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Ltile_manager.engine_tile_manager_sign$type$1$124({1}SC:U),B,1,4
S:Ltile_manager.engine_tile_manager_sign$x$1$124({1}SC:U),B,1,5
S:Ltile_manager.engine_tile_manager_sign$y$1$124({1}SC:U),B,1,6
S:Ltile_manager.engine_tile_manager_sign$wide$1$125({1}SC:U),R,0,0,[b]
S:Ltile_manager.engine_tile_manager_sign$high$1$125({1}SC:U),R,0,0,[d]
F:G$engine_tile_manager_section03$0$0({2}DF,SV:S),Z,0,1,0,0,0
S:Ltile_manager.engine_tile_manager_section03$sect$1$126({1}SC:U),B,1,4
S:Ltile_manager.engine_tile_manager_section03$x$1$126({1}SC:U),B,1,5
S:Ltile_manager.engine_tile_manager_section03$y$1$126({1}SC:U),B,1,6
S:Ltile_manager.engine_tile_manager_section03$tiles$1$127({2}DG,SC:U),R,0,0,[]
S:Ltile_manager.engine_tile_manager_section03$array$1$127({2}DG,SC:U),R,0,0,[]
S:Ltile_manager.engine_tile_manager_section03$idx$1$127({1}SC:U),B,1,-1
S:Ltile_manager.engine_tile_manager_section03$col$1$127({1}SC:U),R,0,0,[d]
S:Ltile_manager.engine_tile_manager_section03$spc$1$127({1}SC:U),R,0,0,[e]
F:G$engine_tile_manager_sky$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Ltile_manager.engine_tile_manager_sky$tiles$1$132({2}DG,SC:U),R,0,0,[]
S:Ltile_manager.engine_tile_manager_sky$idx$1$132({1}SC:U),R,0,0,[]
S:Ltile_manager.engine_tile_manager_sky$row$1$132({1}SC:U),R,0,0,[c]
S:Ltile_manager.engine_tile_manager_sky$col$1$132({1}SC:U),R,0,0,[b]
F:G$engine_tile_manager_sea$0$0({2}DF,SV:S),Z,0,4,0,0,0
S:Ltile_manager.engine_tile_manager_sea$tiles$1$137({2}DG,SC:U),R,0,0,[]
S:Ltile_manager.engine_tile_manager_sea$array$1$137({2}DG,SC:U),R,0,0,[c,b]
S:Ltile_manager.engine_tile_manager_sea$wide$1$137({1}SC:U),B,1,-6
S:Ltile_manager.engine_tile_manager_sea$high$1$137({1}SC:U),B,1,-7
S:Ltile_manager.engine_tile_manager_sea$idx$1$137({1}SC:U),R,0,0,[l]
S:Ltile_manager.engine_tile_manager_sea$val$1$137({1}SC:U),B,1,-8
S:Ltile_manager.engine_tile_manager_sea$row$1$137({1}SC:U),R,0,0,[e]
S:Ltile_manager.engine_tile_manager_sea$col$1$137({1}SC:U),R,0,0,[d]
S:Ltile_manager.engine_tile_manager_sea$mul$1$137({1}SC:U),B,1,-9
S:Ltile_manager.engine_tile_manager_sea$x$1$137({1}SC:U),R,0,0,[]
S:Ltile_manager.engine_tile_manager_sea$y$1$137({1}SC:U),R,0,0,[]
S:Ltile_manager.engine_tile_manager_sea$sloc0$1$0({1}SC:U),B,1,-5
S:Ltile_manager.engine_tile_manager_sea$sloc1$1$0({1}SC:U),B,1,-4
S:Ltile_manager.engine_tile_manager_sea$sloc2$1$0({1}SC:U),B,1,-1
S:Ltile_manager.engine_tile_manager_sea$sloc3$1$0({2}SI:S),B,1,-3
S:G$tile_object_data$0$0({0}DA0d,DG,SC:U),E,0,0
S:G$devkit_SMS_init$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_VDPturnOnFeature$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_VDPturnOffFeature$0$0({2}DF,SV:S),C,0,0
S:G$devkit_VDPFEATURE_EXTRAHEIGHT$0$0({2}DF,SI:U),C,0,0
S:G$devkit_VDPFEATURE_SHIFTSPRITES$0$0({2}DF,SI:U),C,0,0
S:G$devkit_VDPFEATURE_HIDEFIRSTCOL$0$0({2}DF,SI:U),C,0,0
S:G$devkit_VDPFEATURE_LEFTCOLBLANK$0$0({2}DF,SI:U),C,0,0
S:G$devkit_VDPFEATURE_LOCKHSCROLL$0$0({2}DF,SI:U),C,0,0
S:G$devkit_VDPFEATURE_LOCKVSCROLL$0$0({2}DF,SI:U),C,0,0
S:G$devkit_VDPFEATURE_ZOOMSPRITES$0$0({2}DF,SI:U),C,0,0
S:G$devkit_VDPFEATURE_USETALLSPRITES$0$0({2}DF,SI:U),C,0,0
S:G$devkit_VDPFEATURE_240LINES$0$0({2}DF,SI:U),C,0,0
S:G$devkit_VDPFEATURE_224LINES$0$0({2}DF,SI:U),C,0,0
S:G$devkit_VDPFEATURE_FRAMEIRQ$0$0({2}DF,SI:U),C,0,0
S:G$devkit_VDPFEATURE_SHOWDISPLAY$0$0({2}DF,SI:U),C,0,0
S:G$devkit_SMS_displayOn$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_displayOff$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setBGScrollX$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setBGScrollY$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setBackdropColor$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_useFirstHalfTilesforSprites$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setSpriteMode$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SPRITEMODE_NORMAL$0$0({2}DF,SC:U),C,0,0
S:G$devkit_SPRITEMODE_TALL$0$0({2}DF,SC:U),C,0,0
S:G$devkit_SPRITEMODE_ZOOMED$0$0({2}DF,SC:U),C,0,0
S:G$devkit_SPRITEMODE_TALL_ZOOMED$0$0({2}DF,SC:U),C,0,0
S:G$devkit_SMS_mapROMBank$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_enableSRAM$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_enableSRAMBank$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_disableSRAM$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_SRAM$0$0({2}DF,DG,SC:U),C,0,0
S:G$devkit_SMS_waitForVBlank$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadTiles$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadPSGaidencompressedTiles$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadTileMap$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadSTMcompressedTileMapArea$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadTileMapArea$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadSTMcompressedTileMap$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_crt0_RST08$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_crt0_RST18$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setTile$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setAddr$0$0({2}DF,SV:S),C,0,0
S:G$devkit_XYtoADDR$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setNextTileatXY$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setNextTileatLoc$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setNextTileatAddr$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setTileatXY$0$0({2}DF,SV:S),C,0,0
S:G$devkit_TILE_FLIPPED_X$0$0({2}DF,SI:U),C,0,0
S:G$devkit_TILE_FLIPPED_Y$0$0({2}DF,SI:U),C,0,0
S:G$devkit_TILE_USE_SPRITE_PALETTE$0$0({2}DF,SI:U),C,0,0
S:G$devkit_TILE_PRIORITY$0$0({2}DF,SI:U),C,0,0
S:G$devkit_SMS_initSprites$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_addSprite$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_reserveSprite$0$0({2}DF,SC:S),C,0,0
S:G$devkit_SMS_updateSpritePosition$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_updateSpriteImage$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_hideSprite$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setClippingWindow$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_addSpriteClipping$0$0({2}DF,SC:S),C,0,0
S:G$devkit_SMS_finalizeSprites$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_copySpritestoSAT$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setBGPaletteColor$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setSpritePaletteColor$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadBGPalette$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadSpritePalette$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setNextBGColoratIndex$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setNextSpriteColoratIndex$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setColor$0$0({2}DF,SV:S),C,0,0
S:G$devkit_RGB$0$0({2}DF,SC:U),C,0,0
S:G$devkit_RGB8$0$0({2}DF,SC:U),C,0,0
S:G$devkit_SMS_loadBGPaletteHalfBrightness$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadSpritePaletteHalfBrightness$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_zeroBGPalette$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_zeroSpritePalette$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_getKeysStatus$0$0({2}DF,SI:U),C,0,0
S:G$devkit_SMS_getKeysPressed$0$0({2}DF,SI:U),C,0,0
S:G$devkit_SMS_getKeysHeld$0$0({2}DF,SI:U),C,0,0
S:G$devkit_SMS_getKeysReleased$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_A_KEY_UP$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_A_KEY_DOWN$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_A_KEY_LEFT$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_A_KEY_RIGHT$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_A_KEY_1$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_A_KEY_2$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_A_KEY_START$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_B_KEY_UP$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_B_KEY_DOWN$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_B_KEY_LEFT$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_B_KEY_RIGHT$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_B_KEY_1$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_B_KEY_2$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_B_KEY_START$0$0({2}DF,SI:U),C,0,0
S:G$devkit_RESET_KEY$0$0({2}DF,SI:U),C,0,0
S:G$devkit_CARTRIDGE_SLOT$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_A_TH$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_B_TH$0$0({2}DF,SI:U),C,0,0
S:G$devkit_SMS_queryPauseRequested$0$0({2}DF,SC:U),C,0,0
S:G$devkit_SMS_resetPauseRequest$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_VDPFlags$0$0({2}DF,SC:U),C,0,0
S:G$devkit_VDPFLAG_SPRITEOVERFLOW$0$0({2}DF,SC:U),C,0,0
S:G$devkit_VDPFLAG_SPRITECOLLISION$0$0({2}DF,SC:U),C,0,0
S:G$devkit_SMS_setLineInterruptHandler$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setLineCounter$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_enableLineInterrupt$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_disableLineInterrupt$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_VRAMmemcpy$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_VRAMmemcpy_brief$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_VRAMmemset$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_VRAMmemsetW$0$0({2}DF,SV:S),C,0,0
S:G$devkit_UNSAFE_SMS_copySpritestoSAT$0$0({2}DF,SV:S),C,0,0
S:G$devkit_UNSAFE_SMS_VRAMmemcpy32$0$0({2}DF,SV:S),C,0,0
S:G$devkit_UNSAFE_SMS_VRAMmemcpy64$0$0({2}DF,SV:S),C,0,0
S:G$devkit_UNSAFE_SMS_VRAMmemcpy128$0$0({2}DF,SV:S),C,0,0
S:G$devkit_UNSAFE_SMS_load1Tile$0$0({2}DF,SV:S),C,0,0
S:G$devkit_UNSAFE_SMS_load2Tiles$0$0({2}DF,SV:S),C,0,0
S:G$devkit_UNSAFE_SMS_load4Tiles$0$0({2}DF,SV:S),C,0,0
S:G$dekvit_SMS_isr$0$0({2}DF,SV:S),C,0,0
S:G$dekvit_SMS_nmi_isr$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_addSprite_bulk8$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_addSprite_bulk12$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setTilePriority$0$0({2}DF,SV:S),C,0,0
S:G$devkit_isCollisionDetected$0$0({2}DF,SC:U),C,0,0
