M:tile_manager
F:G$engine_tile_manager_draw_pipe$0$0({2}DF,SV:S),Z,0,2,0,0,0
S:Ltile_manager.engine_tile_manager_draw_pipe$type$1$73({1}SC:U),B,1,4
S:Ltile_manager.engine_tile_manager_draw_pipe$x$1$73({2}SI:U),B,1,5
S:Ltile_manager.engine_tile_manager_draw_pipe$y$1$73({1}SC:U),B,1,7
S:Ltile_manager.engine_tile_manager_draw_pipe$wide$1$73({1}SC:U),B,1,8
S:Ltile_manager.engine_tile_manager_draw_pipe$high$1$73({1}SC:U),B,1,9
S:Ltile_manager.engine_tile_manager_draw_pipe$col$1$73({1}SC:U),B,1,10
S:Ltile_manager.engine_tile_manager_draw_pipe$tiles$1$74({2}DG,SC:U),R,0,0,[]
S:Ltile_manager.engine_tile_manager_draw_pipe$array$1$74({2}DG,SC:U),B,1,-3
S:Ltile_manager.engine_tile_manager_draw_pipe$idx$1$74({1}SC:U),R,0,0,[e]
S:Ltile_manager.engine_tile_manager_draw_pipe$val$1$74({1}SC:U),R,0,0,[l]
S:Ltile_manager.engine_tile_manager_draw_pipe$off$1$74({2}SI:U),R,0,0,[l,h]
S:Ltile_manager.engine_tile_manager_draw_pipe$row$1$74({1}SC:U),R,0,0,[c]
S:Ltile_manager.engine_tile_manager_draw_pipe$sloc0$1$0({1}SC:U),B,1,-1
F:G$engine_tile_manager_draw_norm$0$0({2}DF,SV:S),Z,0,2,0,0,0
S:Ltile_manager.engine_tile_manager_draw_norm$type$1$77({1}SC:U),B,1,4
S:Ltile_manager.engine_tile_manager_draw_norm$x$1$77({1}SC:U),B,1,5
S:Ltile_manager.engine_tile_manager_draw_norm$y$1$77({1}SC:U),B,1,6
S:Ltile_manager.engine_tile_manager_draw_norm$wide$1$77({1}SC:U),B,1,7
S:Ltile_manager.engine_tile_manager_draw_norm$high$1$77({1}SC:U),B,1,8
S:Ltile_manager.engine_tile_manager_draw_norm$beg$1$77({1}SC:U),B,1,9
S:Ltile_manager.engine_tile_manager_draw_norm$end$1$77({1}SC:U),B,1,10
S:Ltile_manager.engine_tile_manager_draw_norm$tiles$1$78({2}DG,SC:U),R,0,0,[]
S:Ltile_manager.engine_tile_manager_draw_norm$array$1$78({2}DG,SC:U),B,1,-5
S:Ltile_manager.engine_tile_manager_draw_norm$idx$1$78({1}SC:U),R,0,0,[e]
S:Ltile_manager.engine_tile_manager_draw_norm$val$1$78({1}SC:U),R,0,0,[e]
S:Ltile_manager.engine_tile_manager_draw_norm$row$1$78({1}SC:U),R,0,0,[c]
S:Ltile_manager.engine_tile_manager_draw_norm$col$1$78({1}SC:U),R,0,0,[]
S:Ltile_manager.engine_tile_manager_draw_norm$spc$1$78({1}SC:U),R,0,0,[b]
S:Ltile_manager.engine_tile_manager_draw_norm$sloc0$1$0({1}SC:U),B,1,-2
S:Ltile_manager.engine_tile_manager_draw_norm$sloc1$1$0({1}SC:U),B,1,-1
S:Ltile_manager.engine_tile_manager_draw_norm$sloc2$1$0({1}SC:U),B,1,-3
F:G$engine_tile_manager_draw_flip$0$0({2}DF,SV:S),Z,0,4,0,0,0
S:Ltile_manager.engine_tile_manager_draw_flip$type$1$83({1}SC:U),B,1,4
S:Ltile_manager.engine_tile_manager_draw_flip$x$1$83({1}SC:U),B,1,5
S:Ltile_manager.engine_tile_manager_draw_flip$y$1$83({1}SC:U),B,1,6
S:Ltile_manager.engine_tile_manager_draw_flip$wide$1$83({1}SC:U),B,1,7
S:Ltile_manager.engine_tile_manager_draw_flip$high$1$83({1}SC:U),B,1,8
S:Ltile_manager.engine_tile_manager_draw_flip$beg$1$83({1}SC:U),B,1,9
S:Ltile_manager.engine_tile_manager_draw_flip$end$1$83({1}SC:U),B,1,10
S:Ltile_manager.engine_tile_manager_draw_flip$tiles$1$84({2}DG,SC:U),R,0,0,[]
S:Ltile_manager.engine_tile_manager_draw_flip$array$1$84({2}DG,SC:U),B,1,-5
S:Ltile_manager.engine_tile_manager_draw_flip$idx$1$84({1}SC:U),R,0,0,[e]
S:Ltile_manager.engine_tile_manager_draw_flip$val$1$84({1}SC:U),R,0,0,[e]
S:Ltile_manager.engine_tile_manager_draw_flip$row$1$84({1}SC:U),R,0,0,[c]
S:Ltile_manager.engine_tile_manager_draw_flip$col$1$84({1}SC:U),R,0,0,[e]
S:Ltile_manager.engine_tile_manager_draw_flip$spc$1$84({1}SC:U),R,0,0,[b]
S:Ltile_manager.engine_tile_manager_draw_flip$tmp$1$84({1}SC:U),R,0,0,[]
S:Ltile_manager.engine_tile_manager_draw_flip$flip$1$84({2}SI:U),B,1,-7
S:Ltile_manager.engine_tile_manager_draw_flip$sloc0$1$0({1}SC:U),B,1,-1
S:Ltile_manager.engine_tile_manager_draw_flip$sloc1$1$0({1}SC:U),B,1,-2
S:Ltile_manager.engine_tile_manager_draw_flip$sloc2$1$0({1}SC:U),B,1,-3
F:G$engine_tile_manager_draw_tile$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Ltile_manager.engine_tile_manager_draw_tile$type$1$89({1}SC:U),B,1,4
S:Ltile_manager.engine_tile_manager_draw_tile$x$1$89({1}SC:U),B,1,5
S:Ltile_manager.engine_tile_manager_draw_tile$y$1$89({1}SC:U),B,1,6
S:Ltile_manager.engine_tile_manager_draw_tile$wide$1$90({1}SC:U),R,0,0,[b]
S:Ltile_manager.engine_tile_manager_draw_tile$high$1$90({1}SC:U),R,0,0,[d]
F:G$engine_tile_manager_turtle$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Ltile_manager.engine_tile_manager_turtle$type$1$91({1}SC:U),B,1,4
S:Ltile_manager.engine_tile_manager_turtle$x$1$91({1}SC:U),B,1,5
S:Ltile_manager.engine_tile_manager_turtle$y$1$91({1}SC:U),B,1,6
S:Ltile_manager.engine_tile_manager_turtle$wide$1$92({1}SC:U),R,0,0,[]
S:Ltile_manager.engine_tile_manager_turtle$high$1$92({1}SC:U),R,0,0,[]
F:G$engine_tile_manager_sign$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Ltile_manager.engine_tile_manager_sign$type$1$93({1}SC:U),B,1,4
S:Ltile_manager.engine_tile_manager_sign$x$1$93({1}SC:U),B,1,5
S:Ltile_manager.engine_tile_manager_sign$y$1$93({1}SC:U),B,1,6
S:Ltile_manager.engine_tile_manager_sign$wide$1$94({1}SC:U),R,0,0,[]
S:Ltile_manager.engine_tile_manager_sign$high$1$94({1}SC:U),R,0,0,[]
F:G$engine_tile_manager_scroll_test$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Ltile_manager.engine_tile_manager_scroll_test$x$1$95({1}SC:U),B,1,4
S:Ltile_manager.engine_tile_manager_scroll_test$y$1$95({1}SC:U),B,1,5
S:Ltile_manager.engine_tile_manager_scroll_test$col$1$95({1}SC:U),B,1,6
S:Ltile_manager.engine_tile_manager_scroll_test$array$1$96({2}DG,SC:U),R,0,0,[c,b]
S:Ltile_manager.engine_tile_manager_scroll_test$w$1$96({1}SC:U),R,0,0,[e]
S:Ltile_manager.engine_tile_manager_scroll_test$h$1$96({1}SC:U),R,0,0,[d]
F:G$engine_tile_manager_sky$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Ltile_manager.engine_tile_manager_sky$tiles$1$97({2}DG,SC:U),R,0,0,[]
S:Ltile_manager.engine_tile_manager_sky$idx$1$97({1}SC:U),R,0,0,[]
S:Ltile_manager.engine_tile_manager_sky$row$1$97({1}SC:U),R,0,0,[c]
S:Ltile_manager.engine_tile_manager_sky$col$1$97({1}SC:U),R,0,0,[b]
F:G$engine_tile_manager_sea$0$0({2}DF,SV:S),Z,0,4,0,0,0
S:Ltile_manager.engine_tile_manager_sea$tiles$1$102({2}DG,SC:U),R,0,0,[]
S:Ltile_manager.engine_tile_manager_sea$array$1$102({2}DG,SC:U),R,0,0,[c,b]
S:Ltile_manager.engine_tile_manager_sea$wide$1$102({1}SC:U),B,1,-7
S:Ltile_manager.engine_tile_manager_sea$high$1$102({1}SC:U),B,1,-8
S:Ltile_manager.engine_tile_manager_sea$idx$1$102({1}SC:U),R,0,0,[l]
S:Ltile_manager.engine_tile_manager_sea$val$1$102({1}SC:U),B,1,-6
S:Ltile_manager.engine_tile_manager_sea$row$1$102({1}SC:U),R,0,0,[e]
S:Ltile_manager.engine_tile_manager_sea$col$1$102({1}SC:U),R,0,0,[d]
S:Ltile_manager.engine_tile_manager_sea$mul$1$102({1}SC:U),B,1,-9
S:Ltile_manager.engine_tile_manager_sea$x$1$102({1}SC:U),R,0,0,[]
S:Ltile_manager.engine_tile_manager_sea$y$1$102({1}SC:U),R,0,0,[]
S:Ltile_manager.engine_tile_manager_sea$sloc0$1$0({1}SC:U),B,1,-1
S:Ltile_manager.engine_tile_manager_sea$sloc1$1$0({1}SC:U),B,1,-2
S:Ltile_manager.engine_tile_manager_sea$sloc2$1$0({1}SC:U),B,1,-5
S:Ltile_manager.engine_tile_manager_sea$sloc3$1$0({2}SI:S),B,1,-4
F:Ftile_manager$draw_tile_scroll$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Ltile_manager.draw_tile_scroll$array$1$109({2}DG,SC:U),B,1,4
S:Ltile_manager.draw_tile_scroll$x$1$109({1}SC:U),B,1,6
S:Ltile_manager.draw_tile_scroll$y$1$109({1}SC:U),B,1,7
S:Ltile_manager.draw_tile_scroll$w$1$109({1}SC:U),B,1,8
S:Ltile_manager.draw_tile_scroll$h$1$109({1}SC:U),B,1,9
S:Ltile_manager.draw_tile_scroll$col$1$109({1}SC:U),B,1,10
S:Ltile_manager.draw_tile_scroll$tiles$1$110({2}DG,SC:U),R,0,0,[]
S:Ltile_manager.draw_tile_scroll$idx$1$110({1}SC:U),R,0,0,[e]
S:Ltile_manager.draw_tile_scroll$val$1$110({1}SC:U),R,0,0,[l]
S:Ltile_manager.draw_tile_scroll$off$1$110({2}SI:U),R,0,0,[l,h]
S:Ltile_manager.draw_tile_scroll$row$1$110({1}SC:U),R,0,0,[c]
S:Ltile_manager.draw_tile_scroll$sloc0$1$0({1}SC:U),B,1,-1
S:G$tile_object_data$0$0({0}DA0d,DG,SC:U),E,0,0
S:G$devkit_SMS_init$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_VDPturnOnFeature$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_VDPturnOffFeature$0$0({2}DF,SV:S),C,0,0
S:G$devkit_VDPFEATURE_EXTRAHEIGHT$0$0({2}DF,SI:U),C,0,0
S:G$devkit_VDPFEATURE_SHIFTSPRITES$0$0({2}DF,SI:U),C,0,0
S:G$devkit_VDPFEATURE_HIDEFIRSTCOL$0$0({2}DF,SI:U),C,0,0
S:G$devkit_VDPFEATURE_LEFTCOLBLANK$0$0({2}DF,SI:U),C,0,0
S:G$devkit_VDPFEATURE_LOCKHSCROLL$0$0({2}DF,SI:U),C,0,0
S:G$devkit_VDPFEATURE_LOCKVSCROLL$0$0({2}DF,SI:U),C,0,0
S:G$devkit_VDPFEATURE_ZOOMSPRITES$0$0({2}DF,SI:U),C,0,0
S:G$devkit_VDPFEATURE_USETALLSPRITES$0$0({2}DF,SI:U),C,0,0
S:G$devkit_VDPFEATURE_240LINES$0$0({2}DF,SI:U),C,0,0
S:G$devkit_VDPFEATURE_224LINES$0$0({2}DF,SI:U),C,0,0
S:G$devkit_VDPFEATURE_FRAMEIRQ$0$0({2}DF,SI:U),C,0,0
S:G$devkit_VDPFEATURE_SHOWDISPLAY$0$0({2}DF,SI:U),C,0,0
S:G$devkit_SMS_displayOn$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_displayOff$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setBGScrollX$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setBGScrollY$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setBackdropColor$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_useFirstHalfTilesforSprites$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setSpriteMode$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SPRITEMODE_NORMAL$0$0({2}DF,SC:U),C,0,0
S:G$devkit_SPRITEMODE_TALL$0$0({2}DF,SC:U),C,0,0
S:G$devkit_SPRITEMODE_ZOOMED$0$0({2}DF,SC:U),C,0,0
S:G$devkit_SPRITEMODE_TALL_ZOOMED$0$0({2}DF,SC:U),C,0,0
S:G$devkit_SMS_mapROMBank$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_enableSRAM$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_enableSRAMBank$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_disableSRAM$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_SRAM$0$0({2}DF,DG,SC:U),C,0,0
S:G$devkit_SMS_waitForVBlank$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadTiles$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadPSGaidencompressedTiles$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadTileMap$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadSTMcompressedTileMapArea$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadTileMapArea$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadSTMcompressedTileMap$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_crt0_RST08$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_crt0_RST18$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setTile$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setAddr$0$0({2}DF,SV:S),C,0,0
S:G$devkit_XYtoADDR$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setNextTileatXY$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setNextTileatLoc$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setNextTileatAddr$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setTileatXY$0$0({2}DF,SV:S),C,0,0
S:G$devkit_TILE_FLIPPED_X$0$0({2}DF,SI:U),C,0,0
S:G$devkit_TILE_FLIPPED_Y$0$0({2}DF,SI:U),C,0,0
S:G$devkit_TILE_USE_SPRITE_PALETTE$0$0({2}DF,SI:U),C,0,0
S:G$devkit_TILE_PRIORITY$0$0({2}DF,SI:U),C,0,0
S:G$devkit_SMS_initSprites$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_addSprite$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_reserveSprite$0$0({2}DF,SC:S),C,0,0
S:G$devkit_SMS_updateSpritePosition$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_updateSpriteImage$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_hideSprite$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setClippingWindow$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_addSpriteClipping$0$0({2}DF,SC:S),C,0,0
S:G$devkit_SMS_finalizeSprites$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_copySpritestoSAT$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setBGPaletteColor$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setSpritePaletteColor$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadBGPalette$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadSpritePalette$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setNextBGColoratIndex$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setNextSpriteColoratIndex$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setColor$0$0({2}DF,SV:S),C,0,0
S:G$devkit_RGB$0$0({2}DF,SC:U),C,0,0
S:G$devkit_RGB8$0$0({2}DF,SC:U),C,0,0
S:G$devkit_SMS_loadBGPaletteHalfBrightness$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadSpritePaletteHalfBrightness$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_zeroBGPalette$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_zeroSpritePalette$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_getKeysStatus$0$0({2}DF,SI:U),C,0,0
S:G$devkit_SMS_getKeysPressed$0$0({2}DF,SI:U),C,0,0
S:G$devkit_SMS_getKeysHeld$0$0({2}DF,SI:U),C,0,0
S:G$devkit_SMS_getKeysReleased$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_A_KEY_UP$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_A_KEY_DOWN$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_A_KEY_LEFT$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_A_KEY_RIGHT$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_A_KEY_1$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_A_KEY_2$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_A_KEY_START$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_B_KEY_UP$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_B_KEY_DOWN$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_B_KEY_LEFT$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_B_KEY_RIGHT$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_B_KEY_1$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_B_KEY_2$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_B_KEY_START$0$0({2}DF,SI:U),C,0,0
S:G$devkit_RESET_KEY$0$0({2}DF,SI:U),C,0,0
S:G$devkit_CARTRIDGE_SLOT$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_A_TH$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_B_TH$0$0({2}DF,SI:U),C,0,0
S:G$devkit_SMS_queryPauseRequested$0$0({2}DF,SC:U),C,0,0
S:G$devkit_SMS_resetPauseRequest$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_VDPFlags$0$0({2}DF,SC:U),C,0,0
S:G$devkit_VDPFLAG_SPRITEOVERFLOW$0$0({2}DF,SC:U),C,0,0
S:G$devkit_VDPFLAG_SPRITECOLLISION$0$0({2}DF,SC:U),C,0,0
S:G$devkit_SMS_setLineInterruptHandler$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setLineCounter$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_enableLineInterrupt$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_disableLineInterrupt$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_VRAMmemcpy$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_VRAMmemcpy_brief$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_VRAMmemset$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_VRAMmemsetW$0$0({2}DF,SV:S),C,0,0
S:G$devkit_UNSAFE_SMS_copySpritestoSAT$0$0({2}DF,SV:S),C,0,0
S:G$devkit_UNSAFE_SMS_VRAMmemcpy32$0$0({2}DF,SV:S),C,0,0
S:G$devkit_UNSAFE_SMS_VRAMmemcpy64$0$0({2}DF,SV:S),C,0,0
S:G$devkit_UNSAFE_SMS_VRAMmemcpy128$0$0({2}DF,SV:S),C,0,0
S:G$devkit_UNSAFE_SMS_load1Tile$0$0({2}DF,SV:S),C,0,0
S:G$devkit_UNSAFE_SMS_load2Tiles$0$0({2}DF,SV:S),C,0,0
S:G$devkit_UNSAFE_SMS_load4Tiles$0$0({2}DF,SV:S),C,0,0
S:G$dekvit_SMS_isr$0$0({2}DF,SV:S),C,0,0
S:G$dekvit_SMS_nmi_isr$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_addSprite_bulk8$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_addSprite_bulk12$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setTilePriority$0$0({2}DF,SV:S),C,0,0
S:G$devkit_isCollisionDetected$0$0({2}DF,SC:U),C,0,0
