M:game_manager
F:G$engine_game_manager_init$0$0({2}DF,SV:S),Z,0,0,0,0,0
F:G$engine_game_manager_intro_on$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lgame_manager.engine_game_manager_intro_on$go$1$2({2}DG,STtag_struct_game_object:S),R,0,0,[]
F:G$engine_game_manager_intro_off$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lgame_manager.engine_game_manager_intro_off$go$1$3({2}DG,STtag_struct_game_object:S),R,0,0,[]
F:G$engine_game_manager_music_on$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lgame_manager.engine_game_manager_music_on$go$1$4({2}DG,STtag_struct_game_object:S),R,0,0,[]
F:G$engine_game_manager_music_off$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lgame_manager.engine_game_manager_music_off$go$1$5({2}DG,STtag_struct_game_object:S),R,0,0,[]
T:Fgame_manager$tag_struct_game_object[({0}S:S$intro_once$0$0({1}:S),Z,0,0)({1}S:S$play_music$0$0({1}:S),Z,0,0)]
S:G$global_game_object$0$0({2}STtag_struct_game_object:S),E,0,0
