M:select_manager
F:G$engine_select_manager_init$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lselect_manager.engine_select_manager_init$so$1$9({2}DG,STtag_struct_aelect_object:S),R,0,0,[]
S:Lselect_manager.engine_select_manager_init$index$1$9({1}SC:U),R,0,0,[c]
F:G$engine_select_manager_load$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lselect_manager.engine_select_manager_load$index$1$12({1}SC:U),B,1,4
S:Lselect_manager.engine_select_manager_load$x$1$12({1}SC:U),B,1,5
S:Lselect_manager.engine_select_manager_load$y$1$12({1}SC:U),B,1,6
S:Lselect_manager.engine_select_manager_load$option$1$12({1}SC:U),B,1,7
S:Lselect_manager.engine_select_manager_load$so$1$13({2}DG,STtag_struct_aelect_object:S),R,0,0,[]
F:G$engine_select_manager_update$0$0({2}DF,SC:U),Z,0,0,0,0,0
S:Lselect_manager.engine_select_manager_update$index$1$14({1}SC:U),B,1,4
S:Lselect_manager.engine_select_manager_update$so$1$15({2}DG,STtag_struct_aelect_object:S),R,0,0,[]
S:Lselect_manager.engine_select_manager_update$input$1$15({1}SC:U),R,0,0,[l]
F:Fselect_manager$draw_arrows$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lselect_manager.draw_arrows$so$1$21({2}DG,STtag_struct_aelect_object:S),R,0,0,[]
F:Fselect_manager$draw_spaces$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lselect_manager.draw_spaces$so$1$22({2}DG,STtag_struct_aelect_object:S),R,0,0,[]
T:Fselect_manager$tag_struct_aelect_object[({0}S:S$select_index$0$0({4}DA4d,SC:U),Z,0,0)({4}S:S$select_X$0$0({1}SC:U),Z,0,0)({5}S:S$select_Y$0$0({1}SC:U),Z,0,0)({6}S:S$select_min$0$0({1}SC:U),Z,0,0)({7}S:S$select_max$0$0({1}SC:U),Z,0,0)]
S:G$global_select_object$0$0({8}STtag_struct_aelect_object:S),E,0,0
S:G$engine_font_manager_char$0$0({2}DF,SV:S),C,0,0
S:G$engine_font_manager_text$0$0({2}DF,SV:S),C,0,0
S:G$engine_font_manager_data$0$0({2}DF,SV:S),C,0,0
S:G$engine_font_manager_zero$0$0({2}DF,SV:S),C,0,0
S:G$engine_input_manager_update$0$0({2}DF,SV:S),C,0,0
S:G$engine_input_manager_hold$0$0({2}DF,SC:U),C,0,0
S:G$engine_input_manager_move$0$0({2}DF,SC:U),C,0,0
