M:timer_manager
F:G$engine_timer_manager_load$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Ltimer_manager.engine_timer_manager_load$delay$1$2({2}SI:U),B,1,4
S:Ltimer_manager.engine_timer_manager_load$dObj$1$3({2}DG,STtag_struct_timer_object:S),R,0,0,[]
S:Ltimer_manager.engine_timer_manager_load$ho$1$3({2}DG,STtag_struct_hack_object:S),R,0,0,[]
F:G$engine_timer_manager_update$0$0({2}DF,SC:U),Z,0,0,0,0,0
S:Ltimer_manager.engine_timer_manager_update$dObj$1$5({2}DG,STtag_struct_timer_object:S),R,0,0,[]
S:Ltimer_manager.engine_timer_manager_update$test$1$5({1}SC:U),R,0,0,[b]
T:Ftimer_manager$tag_struct_hack_object[({0}S:S$hack_delays$0$0({1}SC:U),Z,0,0)({1}S:S$hack_musics$0$0({1}SC:U),Z,0,0)({2}S:S$hack_sounds$0$0({1}SC:U),Z,0,0)]
T:Ftimer_manager$tag_struct_timer_object[({0}S:S$timer_count$0$0({2}SI:U),Z,0,0)({2}S:S$timer_value$0$0({2}SI:U),Z,0,0)]
S:G$global_hack_object$0$0({3}STtag_struct_hack_object:S),E,0,0
S:G$global_timer_object$0$0({4}STtag_struct_timer_object:S),E,0,0
