M:collision_manager
F:G$engine_collision_manager_initX$0_0$0({2}DF,SV:S),C,0,0,0,0,0
S:Lcollision_manager.engine_collision_manager_initX$difficulty$1_0$7({1}SC:U),B,1,4
F:G$engine_collision_manager_init$0_0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lcollision_manager.engine_collision_manager_init$difficulty$1_0$10({1}SC:U),B,1,4
F:G$engine_collision_manager_player$0_0$0({2}DF,SC:S),Z,0,0,0,0,0
S:Lcollision_manager.engine_collision_manager_player$lookX$1_0$12({1}SC:U),B,1,4
S:Lcollision_manager.engine_collision_manager_player$tileY$1_0$12({1}SC:U),B,1,5
S:Lcollision_manager.engine_collision_manager_player$lookup_platform$1_0$13({1}SC:U),R,0,0,[c]
S:Lcollision_manager.engine_collision_manager_player$player_platform$1_0$13({1}SC:U),B,1,-2
S:Lcollision_manager.engine_collision_manager_player$collisionTile$1_0$13({1}SC:S),R,0,0,[e]
S:Lcollision_manager.engine_collision_manager_player$sloc0$0_1$0({1}SC:U),B,1,-2
S:Lcollision_manager.engine_collision_manager_player$sloc1$0_1$0({1}SC:S),B,1,-1
F:G$engine_collision_manager_finish$0_0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lcollision_manager.engine_collision_manager_finish$lookX$1_0$20({1}SC:U),B,1,4
S:Lcollision_manager.engine_collision_manager_finish$tileY$1_0$20({1}SC:U),B,1,5
S:Lcollision_manager.engine_collision_manager_finish$posnY$1_0$20({1}SC:U),B,1,6
S:Lcollision_manager.engine_collision_manager_finish$player_begY$1_0$20({2}DG,SC:U),B,1,7
S:Lcollision_manager.engine_collision_manager_finish$player_endY$1_0$20({2}DG,SC:U),B,1,9
S:Lcollision_manager.engine_collision_manager_finish$lookup_platform$1_0$21({1}SC:U),R,0,0,[e]
T:Fcollision_manager$tag_struct_level_object[({0}S:S$level_data$0_0$0({2}DG,SC:U),Z,0,0)({2}S:S$level_size$0_0$0({2}SI:U),Z,0,0)({4}S:S$level_bank$0_0$0({1}SC:U),Z,0,0)({5}S:S$level_check$0_0$0({2}SI:U),Z,0,0)({7}S:S$check_width$0_0$0({1}SC:U),Z,0,0)({8}S:S$column_draw$0_0$0({1}SC:U),Z,0,0)]
S:G$level_platforms$0_0$0({0}DA0d,SC:U),E,0,0
S:G$global_level_object$0_0$0({9}STtag_struct_level_object:S),E,0,0
S:Fcollision_manager$collisionDelta$0_0$0({1}SC:U),E,0,0
S:Fcollision_manager$collisionRange$0_0$0({1}SC:U),E,0,0
S:Fcollision_manager$moreForgiving$0_0$0({1}:S),E,0,0
S:G$engine_level_manager_init$0_0$0({2}DF,SV:S),C,0,0
S:G$engine_level_manager_draw_screen$0_0$0({2}DF,SV:S),C,0,0
S:G$engine_level_manager_draw_column$0_0$0({2}DF,SV:S),C,0,0
S:G$engine_collision_manager_initX$0_0$0({2}DF,SV:S),C,0,0
