M:function_manager
F:G$engine_function_manager_convertXYtoZ$0_0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lfunction_manager.engine_function_manager_convertXYtoZ$divide$1_0$5({1}SC:U),B,1,4
S:Lfunction_manager.engine_function_manager_convertXYtoZ$x$1_0$5({1}SC:U),B,1,5
S:Lfunction_manager.engine_function_manager_convertXYtoZ$y$1_0$5({1}SC:U),B,1,6
S:Lfunction_manager.engine_function_manager_convertXYtoZ$z$1_0$5({2}DG,SC:U),B,1,7
F:G$engine_function_manager_convertZtoXY$0_0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lfunction_manager.engine_function_manager_convertZtoXY$divide$1_0$8({1}SC:U),B,1,4
S:Lfunction_manager.engine_function_manager_convertZtoXY$z$1_0$8({1}SC:U),B,1,5
S:Lfunction_manager.engine_function_manager_convertZtoXY$x$1_0$8({2}DG,SC:U),B,1,6
S:Lfunction_manager.engine_function_manager_convertZtoXY$y$1_0$8({2}DG,SC:U),B,1,8
F:G$engine_function_manager_convertByteToNibbles$0_0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lfunction_manager.engine_function_manager_convertByteToNibbles$byte$1_0$11({1}SC:U),B,1,4
S:Lfunction_manager.engine_function_manager_convertByteToNibbles$upper_nibble$1_0$11({2}DG,SC:U),B,1,5
S:Lfunction_manager.engine_function_manager_convertByteToNibbles$lower_nibble$1_0$11({2}DG,SC:U),B,1,7
F:G$engine_function_manager_convertNibblesToByte$0_0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lfunction_manager.engine_function_manager_convertNibblesToByte$upper_nibble$1_0$14({1}SC:U),B,1,4
S:Lfunction_manager.engine_function_manager_convertNibblesToByte$lower_nibble$1_0$14({1}SC:U),B,1,5
S:Lfunction_manager.engine_function_manager_convertNibblesToByte$byte$1_0$14({2}DG,SC:U),B,1,6
