M:timer_manager
F:G$engine_delay_manager_load$0_0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Ltimer_manager.engine_delay_manager_load$delay$1_0$7({2}SI:U),B,1,4
S:Ltimer_manager.engine_delay_manager_load$dObj$1_0$8({2}DG,STtag_struct_delay_object:S),R,0,0,[]
S:Ltimer_manager.engine_delay_manager_load$ho$1_0$8({2}DG,STtag_struct_hack_object:S),R,0,0,[]
F:G$engine_delay_manager_update$0_0$0({2}DF,SC:U),Z,0,0,0,0,0
S:Ltimer_manager.engine_delay_manager_update$dObj$1_0$9({2}DG,STtag_struct_delay_object:S),R,0,0,[]
S:Ltimer_manager.engine_delay_manager_update$test$1_0$9({1}SC:U),R,0,0,[c]
F:G$engine_delay_manager_draw$0_0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Ltimer_manager.engine_delay_manager_draw$dObj$1_0$11({2}DG,STtag_struct_delay_object:S),R,0,0,[]
F:G$engine_frame_manager_load$0_0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Ltimer_manager.engine_frame_manager_load$fo$1_0$12({2}DG,STtag_struct_frame_object:S),R,0,0,[]
F:G$engine_frame_manager_update$0_0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Ltimer_manager.engine_frame_manager_update$fo$1_0$13({2}DG,STtag_struct_frame_object:S),R,0,0,[]
F:G$engine_frame_manager_draw$0_0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Ltimer_manager.engine_frame_manager_draw$fo$1_0$15({2}DG,STtag_struct_frame_object:S),R,0,0,[]
F:G$engine_reset_manager_load$0_0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Ltimer_manager.engine_reset_manager_load$delay$1_0$16({1}SC:U),B,1,4
S:Ltimer_manager.engine_reset_manager_load$ro$1_0$17({2}DG,STtag_struct_reset_object:S),R,0,0,[]
F:G$engine_reset_manager_update$0_0$0({2}DF,SC:U),Z,0,0,0,0,0
S:Ltimer_manager.engine_reset_manager_update$ro$1_0$18({2}DG,STtag_struct_reset_object:S),R,0,0,[]
S:Ltimer_manager.engine_reset_manager_update$test$1_0$18({1}SC:U),R,0,0,[e]
F:G$engine_reset_manager_reset$0_0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Ltimer_manager.engine_reset_manager_reset$ro$1_0$20({2}DG,STtag_struct_reset_object:S),R,0,0,[]
T:Ftimer_manager$tag_struct_hack_object[({0}S:S$hack_object_level$0_0$0({1}SC:U),Z,0,0)({1}S:S$hack_object_screen$0_0$0({1}SC:U),Z,0,0)]
T:Ftimer_manager$tag_struct_frame_object[({0}S:S$frame_count$0_0$0({2}SI:U),Z,0,0)]
T:Ftimer_manager$tag_struct_delay_object[({0}S:S$delay_value$0_0$0({2}SI:U),Z,0,0)({2}S:S$delay_timer$0_0$0({2}SI:U),Z,0,0)]
T:Ftimer_manager$tag_struct_reset_object[({0}S:S$reset_value$0_0$0({1}SC:U),Z,0,0)({1}S:S$reset_timer$0_0$0({1}SC:U),Z,0,0)]
S:G$global_hack_object$0_0$0({2}STtag_struct_hack_object:S),E,0,0
S:G$global_delay_object$0_0$0({4}STtag_struct_delay_object:S),E,0,0
S:G$global_frame_object$0_0$0({2}STtag_struct_frame_object:S),E,0,0
S:G$global_reset_object$0_0$0({2}STtag_struct_reset_object:S),E,0,0
S:G$engine_font_manager_char$0_0$0({2}DF,SV:S),C,0,0
S:G$engine_font_manager_text$0_0$0({2}DF,SV:S),C,0,0
S:G$engine_font_manager_data$0_0$0({2}DF,SV:S),C,0,0
S:G$engine_font_manager_zero$0_0$0({2}DF,SV:S),C,0,0
S:G$engine_hack_manager_init$0_0$0({2}DF,SV:S),C,0,0
S:G$engine_hack_manager_load$0_0$0({2}DF,SV:S),C,0,0
S:G$engine_hack_manager_invert$0_0$0({2}DF,SV:S),C,0,0
